# part1: For Beginners Bag Of Words

## 1.数据集导入

In [1]:
import kagglehub

# Download latest version
path = kagglehub.competition_download('word2vec-nlp-tutorial')

print("Path to competition files:", path)

import zipfile
import os

zip_path = '/kaggle/input/competitions/word2vec-nlp-tutorial/labeledTrainData.tsv.zip'
extract_path = '/kaggle/working/'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# 查看解压后的文件
print(os.listdir(extract_path))

Path to competition files: /kaggle/input/competitions/word2vec-nlp-tutorial
['labeledTrainData.tsv', '.virtual_documents']

## 2.数据集读取

In [2]:
# Import the pandas package, then use the "read_csv" function to read
# the labeled training data
import pandas as pd       
train = pd.read_csv("labeledTrainData.tsv", header=0, \
                    delimiter="\t", quoting=3)

# 数据集信息
print ("train shape:",train.shape) # 数据集合形状

print("train columns：",train.columns.values) # 数据列名

print("review[0]：",train["review"][0]) # 第一条影评内容

train shape: (25000, 3)
train columns： ['id' 'sentiment' 'review']
review[0]： "With all this stuff going down at the moment with MJ i've started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ's feeling towards the press and also the obvious message of drugs are bad m'kay.<br /><br />Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.<br /><br />The actual feature film bit when it finally starts is only on for 20 minutes or so excluding the Smooth Criminal sequence and Joe Pesci is convincing as a psychopathic all powerful drug lord. Why he wants MJ dead so bad is beyond me. Because MJ overheard his plans? Nah, Joe Pesci's character ranted that he wanted people to know it is he who is supplying drugs etc so i dunno, maybe he just hates MJ's music.<br /><br />Lots of cool things in this like MJ turning into a car and a robot and the whole Speed Demon sequence. Also, the director must have had the patience of a saint when it came to filming the kiddy Bad sequence as usually directors hate working with one kid let alone a whole bunch of them performing a complex dance scene.<br /><br />Bottom line, this movie is for people who like MJ on one level or another (which i think is most people). If not, then stay away. It does try and give off a wholesome message and ironically MJ's bestest buddy in this movie is a girl! Michael Jackson is truly one of the most talented people ever to grace this planet but is he guilty? Well, with all the attention i've gave this subject....hmmm well i don't know because people can be different behind closed doors, i know this for a fact. He is either an extremely nice but stupid guy or one of the most sickest liars. I hope he is not the latter."

## 3.数据清洗及文本预处理

### 3.1 移除HTML标记:使用 BeautifulSoup 包实现

In [3]:
# Import BeautifulSoup into your workspace
from bs4 import BeautifulSoup             

# Initialize the BeautifulSoup object on a single movie review     
example1 = BeautifulSoup(train["review"][0])  

# Print the raw review and then the output of get_text(), for 
# comparison
print(train["review"][0])
print(example1.get_text())

"With all this stuff going down at the moment with MJ i've started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ's feeling towards the press and also the obvious message of drugs are bad m'kay.<br /><br />Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.<br /><br />The actual feature film bit when it finally starts is only on for 20 minutes or so excluding the Smooth Criminal sequence and Joe Pesci is convincing as a psychopathic all powerful drug lord. Why he wants MJ dead so bad is beyond me. Because MJ overheard his plans? Nah, Joe Pesci's character ranted that he wanted people to know it is he who is supplying drugs etc so i dunno, maybe he just hates MJ's music.<br /><br />Lots of cool things in this like MJ turning into a car and a robot and the whole Speed Demon sequence. Also, the director must have had the patience of a saint when it came to filming the kiddy Bad sequence as usually directors hate working with one kid let alone a whole bunch of them performing a complex dance scene.<br /><br />Bottom line, this movie is for people who like MJ on one level or another (which i think is most people). If not, then stay away. It does try and give off a wholesome message and ironically MJ's bestest buddy in this movie is a girl! Michael Jackson is truly one of the most talented people ever to grace this planet but is he guilty? Well, with all the attention i've gave this subject....hmmm well i don't know because people can be different behind closed doors, i know this for a fact. He is either an extremely nice but stupid guy or one of the most sickest liars. I hope he is not the latter."
"With all this stuff going down at the moment with MJ i've started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ's feeling towards the press and also the obvious message of drugs are bad m'kay.Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.The actual feature film bit when it finally starts is only on for 20 minutes or so excluding the Smooth Criminal sequence and Joe Pesci is convincing as a psychopathic all powerful drug lord. Why he wants MJ dead so bad is beyond me. Because MJ overheard his plans? Nah, Joe Pesci's character ranted that he wanted people to know it is he who is supplying drugs etc so i dunno, maybe he just hates MJ's music.Lots of cool things in this like MJ turning into a car and a robot and the whole Speed Demon sequence. Also, the director must have had the patience of a saint when it came to filming the kiddy Bad sequence as usually directors hate working with one kid let alone a whole bunch of them performing a complex dance scene.Bottom line, this movie is for people who like MJ on one level or another (which i think is most people). If not, then stay away. It does try and give off a wholesome message and ironically MJ's bestest buddy in this movie is a girl! Michael Jackson is truly one of the most talented people ever to grace this planet but is he guilty? Well, with all the attention i've gave this subject....hmmm well i don't know because people can be different behind closed doors, i know this for a fact. He is either an extremely nice but stupid guy or one of the most sickest liars. I hope he is not the latter."

### 3.2 处理标点符号、数字及停用词：使用NLTK（natural language toolkit）和RE（正则表达式）

In [4]:
import re
# Use regular expressions to do a find-and-replace
letters_only = re.sub("[^a-zA-Z]",           # The pattern to search for
                      " ",                   # The pattern to replace it with
                      example1.get_text() )  # The text to search
print(letters_only)

lower_case = letters_only.lower()        # Convert to lower case
words = lower_case.split()               # Split into words


import nltk
nltk.download('stopwords')  # Download text data sets, including stop words

from nltk.corpus import stopwords # Import the stop word list
print(stopwords.words("english"))

# Remove stop words from "words"
words = [w for w in words if not w in stopwords.words("english")]
print(words)

 With all this stuff going down at the moment with MJ i ve started listening to his music  watching the odd documentary here and there  watched The Wiz and watched Moonwalker again  Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent  Moonwalker is part biography  part feature film which i remember going to see at the cinema when it was originally released  Some of it has subtle messages about MJ s feeling towards the press and also the obvious message of drugs are bad m kay Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring  Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him The actual feature film bit when it finally starts is only on for    minutes or so excluding the Smooth Criminal sequence and Joe Pesci is convincing as a psychopathic all powerful drug lord  Why he wants MJ dead so bad is beyond me  Because MJ overheard his plans  Nah  Joe Pesci s character ranted that he wanted people to know it is he who is supplying drugs etc so i dunno  maybe he just hates MJ s music Lots of cool things in this like MJ turning into a car and a robot and the whole Speed Demon sequence  Also  the director must have had the patience of a saint when it came to filming the kiddy Bad sequence as usually directors hate working with one kid let alone a whole bunch of them performing a complex dance scene Bottom line  this movie is for people who like MJ on one level or another  which i think is most people   If not  then stay away  It does try and give off a wholesome message and ironically MJ s bestest buddy in this movie is a girl  Michael Jackson is truly one of the most talented people ever to grace this planet but is he guilty  Well  with all the attention i ve gave this subject    hmmm well i don t know because people can be different behind closed doors  i know this for a fact  He is either an extremely nice but stupid guy or one of the most sickest liars  I hope he is not the latter
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]
['stuff', 'going', 'moment', 'mj', 'started', 'listening', 'music', 'watching', 'odd', 'documentary', 'watched', 'wiz', 'watched', 'moonwalker', 'maybe', 'want', 'get', 'certain', 'insight', 'guy', 'thought', 'really', 'cool', 'eighties', 'maybe', 'make', 'mind', 'whether', 'guilty', 'innocent', 'moonwalker', 'part', 'biography', 'part', 'feature', 'film', 'remember', 'going', 'see', 'cinema', 'originally', 'released', 'subtle', 'messages', 'mj', 'feeling', 'towards', 'press', 'also', 'obvious', 'message', 'drugs', 'bad', 'kay', 'visually', 'impressive', 'course', 'michael', 'jackson', 'unless', 'remotely', 'like', 'mj', 'anyway', 'going', 'hate', 'find', 'boring', 'may', 'call', 'mj', 'egotist', 'consenting', 'making', 'movie', 'mj', 'fans', 'would', 'say', 'made', 'fans', 'true', 'really', 'nice', 'actual', 'feature', 'film', 'bit', 'finally', 'starts', 'minutes', 'excluding', 'smooth', 'criminal', 'sequence', 'joe', 'pesci', 'convincing', 'psychopathic', 'powerful', 'drug', 'lord', 'wants', 'mj', 'dead', 'bad', 'beyond', 'mj', 'overheard', 'plans', 'nah', 'joe', 'pesci', 'character', 'ranted', 'wanted', 'people', 'know', 'supplying', 'drugs', 'etc', 'dunno', 'maybe', 'hates', 'mj', 'music', 'lots', 'cool', 'things', 'like', 'mj', 'turning', 'car', 'robot', 'whole', 'speed', 'demon', 'sequence', 'also', 'director', 'must', 'patience', 'saint', 'came', 'filming', 'kiddy', 'bad', 'sequence', 'usually', 'directors', 'hate', 'working', 'one', 'kid', 'let', 'alone', 'whole', 'bunch', 'performing', 'complex', 'dance', 'scene', 'bottom', 'line', 'movie', 'people', 'like', 'mj', 'one', 'level', 'another', 'think', 'people', 'stay', 'away', 'try', 'give', 'wholesome', 'message', 'ironically', 'mj', 'bestest', 'buddy', 'movie', 'girl', 'michael', 'jackson', 'truly', 'one', 'talented', 'people', 'ever', 'grace', 'planet', 'guilty', 'well', 'attention', 'gave', 'subject', 'hmmm', 'well', 'know', 'people', 'different', 'behind', 'closed', 'doors', 'know', 'fact', 'either', 'extremely', 'nice', 'stupid', 'guy', 'one', 'sickest', 'liars', 'hope', 'latter']

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

### 3.3 整合预处理代码

In [5]:
def review_to_words( raw_review ):
    # Function to convert a raw review to a string of words
    # The input is a single string (a raw movie review), and 
    # the output is a single string (a preprocessed movie review)
    #
    # 1. Remove HTML
    review_text = BeautifulSoup(raw_review).get_text() 
    #
    # 2. Remove non-letters        
    letters_only = re.sub("[^a-zA-Z]", " ", review_text) 
    #
    # 3. Convert to lower case, split into individual words
    words = letters_only.lower().split()                             
    #
    # 4. In Python, searching a set is much faster than searching
    #   a list, so convert the stop words to a set
    stops = set(stopwords.words("english"))                  
    # 
    # 5. Remove stop words
    meaningful_words = [w for w in words if not w in stops]   
    #
    # 6. Join the words back into one string separated by space, 
    # and return the result.
    return( " ".join( meaningful_words ))

clean_review = review_to_words( train["review"][0] )
print(clean_review)

# 使用循环处理全部数据
# Get the number of reviews based on the dataframe column size
num_reviews = train["review"].size

# Initialize an empty list to hold the clean reviews
print("Cleaning and parsing the training set movie reviews...\n")
clean_train_reviews = []
for i in range( 0, num_reviews ):
    # If the index is evenly divisible by 1000, print a message
    if( (i+1)%1000 == 0 ):
        print("Review %d of %d\n" % ( i+1, num_reviews ))                                                                    
    clean_train_reviews.append( review_to_words( train["review"][i] ))

stuff going moment mj started listening music watching odd documentary watched wiz watched moonwalker maybe want get certain insight guy thought really cool eighties maybe make mind whether guilty innocent moonwalker part biography part feature film remember going see cinema originally released subtle messages mj feeling towards press also obvious message drugs bad kay visually impressive course michael jackson unless remotely like mj anyway going hate find boring may call mj egotist consenting making movie mj fans would say made fans true really nice actual feature film bit finally starts minutes excluding smooth criminal sequence joe pesci convincing psychopathic powerful drug lord wants mj dead bad beyond mj overheard plans nah joe pesci character ranted wanted people know supplying drugs etc dunno maybe hates mj music lots cool things like mj turning car robot whole speed demon sequence also director must patience saint came filming kiddy bad sequence usually directors hate working one kid let alone whole bunch performing complex dance scene bottom line movie people like mj one level another think people stay away try give wholesome message ironically mj bestest buddy movie girl michael jackson truly one talented people ever grace planet guilty well attention gave subject hmmm well know people different behind closed doors know fact either extremely nice stupid guy one sickest liars hope latter
Cleaning and parsing the training set movie reviews...

Review 1000 of 25000

Review 2000 of 25000

Review 3000 of 25000

Review 4000 of 25000

Review 5000 of 25000

Review 6000 of 25000

Review 7000 of 25000

Review 8000 of 25000

Review 9000 of 25000

Review 10000 of 25000

Review 11000 of 25000

Review 12000 of 25000

Review 13000 of 25000

Review 14000 of 25000

Review 15000 of 25000

Review 16000 of 25000

Review 17000 of 25000

Review 18000 of 25000

Review 19000 of 25000

Review 20000 of 25000

Review 21000 of 25000

Review 22000 of 25000

Review 23000 of 25000

Review 24000 of 25000

Review 25000 of 25000

## 4. 利用词袋模型创建特征(使用 scikit-learn)

In [6]:
print("Creating the bag of words...\n")
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the "CountVectorizer" object, which is scikit-learn's
# bag of words tool.  
vectorizer = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = None,   \
                             max_features = 5000) 

# fit_transform() does two functions: First, it fits the model
# and learns the vocabulary; second, it transforms our training data
# into feature vectors. The input to fit_transform should be a list of 
# strings.
train_data_features = vectorizer.fit_transform(clean_train_reviews)

# Numpy arrays are easy to work with, so convert the result to an 
# array
train_data_features = train_data_features.toarray()

print("training data array now looks like:",train_data_features.shape)

# Take a look at the words in the vocabulary
vocab = vectorizer.get_feature_names_out()
print("Take a look at the words in the vocabulary:\n",vocab)

Creating the bag of words...

training data array now looks like: (25000, 5000)
Take a look at the words in the vocabulary:
 ['abandoned' 'abc' 'abilities' ... 'zombie' 'zombies' 'zone']

## 5. Random Forest

In [ ]:
print("Training the random forest...")
from sklearn.ensemble import RandomForestClassifier

# Initialize a Random Forest classifier with 100 trees
forest = RandomForestClassifier(n_estimators = 100) 

# Fit the forest to the training set, using the bag of words as 
# features and the sentiment labels as the response variable
#
# This may take a few minutes to run
forest = forest.fit( train_data_features, train["sentiment"] )

## 6.创建Submission

In [ ]:
import zipfile
import os

zip_path = '/kaggle/input/competitions/word2vec-nlp-tutorial/testData.tsv.zip'
output_dir = '/kaggle/working'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(output_dir)

print("testData.tsv 解压完成！当前 working 目录文件：", os.listdir(output_dir))

# Read the test data
test = pd.read_csv("testData.tsv", header=0, delimiter="\t", \
                   quoting=3 )

# Verify that there are 25,000 rows and 2 columns
print(test.shape)

# Create an empty list and append the clean reviews one by one
num_reviews = len(test["review"])
clean_test_reviews = [] 

print("Cleaning and parsing the test set movie reviews...\n")
for i in range(0,num_reviews):
    if( (i+1) % 1000 == 0 ):
        print("Review %d of %d\n" % (i+1, num_reviews))
    clean_review = review_to_words( test["review"][i] )
    clean_test_reviews.append( clean_review )

# Get a bag of words for the test set, and convert to a numpy array
test_data_features = vectorizer.transform(clean_test_reviews)
test_data_features = test_data_features.toarray()

# Use the random forest to make sentiment label predictions
result = forest.predict(test_data_features)

# Copy the results to a pandas dataframe with an "id" column and
# a "sentiment" column
output = pd.DataFrame( data={"id":test["id"], "sentiment":result} )

# Use pandas to write the comma-separated output file
output.to_csv( "Bag_of_Words_model.csv", index=False, quoting=3 )

# part2:Word Vectors

## Preparing to Train a Mode

In [ ]:
import zipfile
import os

zip_path = '/kaggle/input/competitions/word2vec-nlp-tutorial/unlabeledTrainData.tsv.zip'
output_dir = '/kaggle/working'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(output_dir)

print("unlabeledTrainData.tsv解压完成！当前 working 目录文件：", os.listdir(output_dir))

import pandas as pd

# Read data from files 
train = pd.read_csv( "labeledTrainData.tsv", header=0, 
 delimiter="\t", quoting=3 )
test = pd.read_csv( "testData.tsv", header=0, delimiter="\t", quoting=3 )
unlabeled_train = pd.read_csv( "unlabeledTrainData.tsv", header=0, 
 delimiter="\t", quoting=3 )

# Verify the number of reviews that were read (100,000 in total)
print("Read %d labeled train reviews, %d labeled test reviews, " \
 "and %d unlabeled reviews\n" % (train["review"].size,  
 test["review"].size, unlabeled_train["review"].size ))

In [ ]:
# Import various modules for string cleaning
from bs4 import BeautifulSoup
import re
from nltk.corpus import stopwords

def review_to_wordlist( review, remove_stopwords=False ):
    # Function to convert a document to a sequence of words,
    # optionally removing stop words.  Returns a list of words.
    #
    # 1. Remove HTML
    review_text = BeautifulSoup(review).get_text()
    #  
    # 2. Remove non-letters
    review_text = re.sub("[^a-zA-Z]"," ", review_text)
    #
    # 3. Convert words to lower case and split them
    words = review_text.lower().split()
    #
    # 4. Optionally remove stop words (false by default)
    if remove_stopwords:
        stops = set(stopwords.words("english"))
        words = [w for w in words if not w in stops]
    #
    # 5. Return a list of words
    return(words)

In [ ]:
# Download the punkt tokenizer for sentence splitting
import nltk.data
nltk.download("punkt")   

# Load the punkt tokenizer
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

# Define a function to split a review into parsed sentences
def review_to_sentences( review, tokenizer, remove_stopwords=False ):
    # Function to split a review into parsed sentences. Returns a 
    # list of sentences, where each sentence is a list of words
    #
    # 1. Use the NLTK tokenizer to split the paragraph into sentences
    raw_sentences = tokenizer.tokenize(review.strip())
    #
    # 2. Loop over each sentence
    sentences = []
    for raw_sentence in raw_sentences:
        # If a sentence is empty, skip it
        if len(raw_sentence) > 0:
            # Otherwise, call review_to_wordlist to get a list of words
            sentences.append( review_to_wordlist( raw_sentence, \
              remove_stopwords ))
    #
    # Return the list of sentences (each sentence is a list of words,
    # so this returns a list of lists
    return sentences

In [ ]:
sentences = []  # Initialize an empty list of sentences

print("Parsing sentences from training set")
for review in train["review"]:
    sentences += review_to_sentences(review, tokenizer)

print("Parsing sentences from unlabeled set")
for review in unlabeled_train["review"]:
    sentences += review_to_sentences(review, tokenizer)

In [ ]:
print(len(sentences))
print(sentences[0])
print(sentences[1])

## Training and Saving Model

In [ ]:
# Import the built-in logging module and configure it so that Word2Vec 
# creates nice output messages
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s',\
    level=logging.INFO)

# Set values for various parameters
num_features = 300    # Word vector dimensionality                      
min_word_count = 40   # Minimum word count                        
num_workers = 4       # Number of threads to run in parallel
context = 10          # Context window size                                                                                    
downsampling = 1e-3   # Downsample setting for frequent words

# Initialize and train the model (this will take some time)
from gensim.models import word2vec
print("Training model...")
model = word2vec.Word2Vec(sentences, workers=num_workers, \
            vector_size=num_features, min_count = min_word_count, \
            window = context, sample = downsampling)

# If you don't plan to train the model any further, calling 
# init_sims will make the model much more memory-efficient.
model.init_sims(replace=True)

# It can be helpful to create a meaningful model name and 
# save the model for later use. You can load it later using Word2Vec.load()
model_name = "300features_40minwords_10context"
model.save(model_name)

## Exploring the Model Results

In [ ]:
model.wv.doesnt_match("france england germany berlin".split())

In [ ]:
model.wv.doesnt_match("paris berlin london austria".split())

In [ ]:

model.wv.most_similar("man")

In [ ]:
model.wv.most_similar("queen")

In [ ]:
model.wv.most_similar("awful")

In [ ]:
model.wv.doesnt_match("man woman child kitchen".split())

# part3:More Fun With Word Vectors

## Numeric Representations of Words

In [ ]:
# Load the model that we created in Part 2
from gensim.models import Word2Vec
model = Word2Vec.load("300features_40minwords_10context")

type(model.wv.vectors)

model.wv.vectors.shape

In [ ]:
model.wv["flower"]

## From Words To Paragraphs, Attempt 1: Vector Averaging（向量平均）

In [ ]:
import numpy as np  # Make sure that numpy is imported

def makeFeatureVec(words, model, num_features):
    # Function to average all of the word vectors in a given
    # paragraph
    #
    # Pre-initialize an empty numpy array (for speed)
    featureVec = np.zeros((num_features,),dtype="float32")
    #
    nwords = 0.
    # 
    # Index2word is a list that contains the names of the words in 
    # the model's vocabulary. Convert it to a set, for speed 
    index2word_set = set(model.wv.index_to_key)
    #
    # Loop over each word in the review and, if it is in the model's
    # vocaublary, add its feature vector to the total
    for word in words:
        if word in index2word_set: 
            nwords = nwords + 1.
            featureVec = np.add(featureVec,model.wv[word])
    # 
    # Divide the result by the number of words to get the average
    featureVec = np.divide(featureVec,nwords)
    return featureVec


def getAvgFeatureVecs(reviews, model, num_features):
    # Given a set of reviews (each one a list of words), calculate 
    # the average feature vector for each one and return a 2D numpy array 
    # 
    # Initialize a counter
    counter = 0
    # 
    # Preallocate a 2D numpy array, for speed
    reviewFeatureVecs = np.zeros((len(reviews),num_features),dtype="float32")
    # 
    # Loop through the reviews
    for review in reviews:
       #
       # Print a status message every 1000th review
       if counter%1000 == 0:
           print("Review %d of %d" % (counter, len(reviews)))
       # 
       # Call the function (defined above) that makes average feature vectors
       reviewFeatureVecs[counter] = makeFeatureVec(review, model, \
           num_features)
       #
       # Increment the counter
       counter = counter + 1
    return reviewFeatureVecs

print("Done!")

In [ ]:
# ****************************************************************
# Calculate average feature vectors for training and testing sets,
# using the functions we defined above. Notice that we now use stop word
# removal.

clean_train_reviews = []
for review in train["review"]:
    clean_train_reviews.append( review_to_wordlist( review, \
        remove_stopwords=True ))

trainDataVecs = getAvgFeatureVecs( clean_train_reviews, model, num_features )

print("Creating average feature vecs for test reviews")
clean_test_reviews = []
for review in test["review"]:
    clean_test_reviews.append( review_to_wordlist( review, \
        remove_stopwords=True ))

testDataVecs = getAvgFeatureVecs( clean_test_reviews, model, num_features )

In [ ]:
# Fit a random forest to the training data, using 100 trees
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier( n_estimators = 100 )

print("Fitting a random forest to labeled training data...")
forest = forest.fit( trainDataVecs, train["sentiment"] )

# Test & extract results 
result = forest.predict( testDataVecs )

# Write the test results 
output = pd.DataFrame( data={"id":test["id"], "sentiment":result} )
output.to_csv( "Word2Vec_AverageVectors.csv", index=False, quoting=3 )

## From Words to Paragraphs, Attempt 2: Clustering（K-means）

In [ ]:
from sklearn.cluster import KMeans
import time

start = time.time() # Start time

# Set "k" (num_clusters) to be 1/5th of the vocabulary size, or an
# average of 5 words per cluster
word_vectors = model.wv.vectors
num_clusters = int(word_vectors.shape[0] / 5)

# Initalize a k-means object and use it to extract centroids
kmeans_clustering = KMeans( n_clusters = num_clusters )
idx = kmeans_clustering.fit_predict( word_vectors )

# Get the end time and print how long the process took
end = time.time()
elapsed = end - start
print("Time taken for K Means clustering: ", elapsed, "seconds.")

In [ ]:
# Create a Word / Index dictionary, mapping each vocabulary word to
# a cluster number                                                                                            
word_centroid_map = dict(zip( model.wv.index_to_key, idx ))

In [ ]:
# For the first 10 clusters
for cluster in range(0,10):
    #
    # Print the cluster number  
    print("\nCluster %d" % cluster)
    #
    # Find all of the words for that cluster number, and print them out
    words = [word for word, cluster_id in word_centroid_map.items() if cluster_id == cluster]
    print(words)

In [ ]:
def create_bag_of_centroids( wordlist, word_centroid_map ):
    #
    # The number of clusters is equal to the highest cluster index
    # in the word / centroid map
    num_centroids = max( word_centroid_map.values() ) + 1
    #
    # Pre-allocate the bag of centroids vector (for speed)
    bag_of_centroids = np.zeros( num_centroids, dtype="float32" )
    #
    # Loop over the words in the review. If the word is in the vocabulary,
    # find which cluster it belongs to, and increment that cluster count 
    # by one
    for word in wordlist:
        if word in word_centroid_map:
            index = word_centroid_map[word]
            bag_of_centroids[index] += 1
    #
    # Return the "bag of centroids"
    return bag_of_centroids

print("Done!")

In [ ]:
# Pre-allocate an array for the training set bags of centroids (for speed)
train_centroids = np.zeros( (train["review"].size, num_clusters), \
    dtype="float32" )

# Transform the training set reviews into bags of centroids
counter = 0
for review in clean_train_reviews:
    train_centroids[counter] = create_bag_of_centroids( review, \
        word_centroid_map )
    counter += 1

# Repeat for test reviews 
test_centroids = np.zeros(( test["review"].size, num_clusters), \
    dtype="float32" )

counter = 0
for review in clean_test_reviews:
    test_centroids[counter] = create_bag_of_centroids( review, \
        word_centroid_map )
    counter += 1

print("Done!")

In [ ]:
# Fit a random forest and extract predictions 
forest = RandomForestClassifier(n_estimators = 100)

# Fitting the forest may take a few minutes
print("Fitting a random forest to labeled training data...")
forest = forest.fit(train_centroids,train["sentiment"])
result = forest.predict(test_centroids)

# Write the test results 
output = pd.DataFrame(data={"id":test["id"], "sentiment":result})
output.to_csv( "BagOfCentroids.csv", index=False, quoting=3 )

#  拓展实验

## 数据解压

In [2]:
# 解压数据
import glob
import os
import zipfile

# 压缩包所在的文件夹路径与解压目标路径
zip_dir = "/kaggle/input/competitions/word2vec-nlp-tutorial"  # 存放多个 zip 的文件夹
output_dir = "/kaggle/working/"  # 解压出来的目标文件夹

# 获取所有 .zip 文件的路径
zip_files = glob.glob(os.path.join(zip_dir, "*.zip"))

for file_path in zip_files:
    print(f"正在解压: {file_path}")
    with zipfile.ZipFile(file_path, "r") as zip_ref:
        # 解压到统一的目标文件夹（如果想按文件名单独建文件夹，可用下面的方法）
        zip_ref.extractall(output_dir)

print("所有 ZIP 文件解压完成！")

os.makedirs("./result", exist_ok=True)

正在解压: /kaggle/input/competitions/word2vec-nlp-tutorial/testData.tsv.zip
正在解压: /kaggle/input/competitions/word2vec-nlp-tutorial/unlabeledTrainData.tsv.zip
正在解压: /kaggle/input/competitions/word2vec-nlp-tutorial/labeledTrainData.tsv.zip
所有 ZIP 文件解压完成！

In [2]:
#  模型下载

!wget --content-disposition https://huggingface.co/stanfordnlp/glove/resolve/main/glove.840B.300d.zip

--2026-09-25 05:43:49--  https://huggingface.co/stanfordnlp/glove/resolve/main/glove.840B.300d.zip
Resolving huggingface.co (huggingface.co)... 3.171.171.128, 3.171.171.65, 3.171.171.104, ...
Connecting to huggingface.co (huggingface.co)|3.171.171.128|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://us.gcp.cdn.hf.co/xet-bridge-us/621ffdc136468d709f18095d/33769eb990aac86c1a663ae599d07e6f9d56a7d4221e250087fe384ac5628a52?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27glove.840B.300d.zip%3B+filename%3D%22glove.840B.300d.zip%22%3B&response-content-type=application%2Fzip&user_id=public&X-Xet-Cas-Uid=public&Expires=1790318629&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjIxZmZkYzEzNjQ2OGQ3MDlmMTgwOTVkLzMzNzY5ZWI5OTBhYWM4NmMxYTY2M2FlNTk5ZDA3ZTZmOWQ1NmE3ZDQyMjFlMjUwMDg3ZmUzODRhYzU2MjhhNTJcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSomcmVzcG9uc2UtY29udGVudC10eXBlPSomdXNlcl9pZD1wdWJsaWMmWC1YZXQtQ2FzLVVpZD1wdWJsaWMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkVwb2NoVGltZSI6MTc5MDMxODYyOX19fV19&Signature=MEYCIQCqQy7PO56L33i3lcb1UUNloyu%7EyxghVFE9u5mmAb21PgIhALFaSkuiCt%7EoVx2HYQ66G7YtZ8CCSPV-QqFt256QYD-s&Key-Pair-Id=01KXEF4KZ1B6FV465MAWR4M21F&Hash-Algorithm=SHA256 [following]
--2026-09-25 05:43:49--  https://us.gcp.cdn.hf.co/xet-bridge-us/621ffdc136468d709f18095d/33769eb990aac86c1a663ae599d07e6f9d56a7d4221e250087fe384ac5628a52?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27glove.840B.300d.zip%3B+filename%3D%22glove.840B.300d.zip%22%3B&response-content-type=application%2Fzip&user_id=public&X-Xet-Cas-Uid=public&Expires=1790318629&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjIxZmZkYzEzNjQ2OGQ3MDlmMTgwOTVkLzMzNzY5ZWI5OTBhYWM4NmMxYTY2M2FlNTk5ZDA3ZTZmOWQ1NmE3ZDQyMjFlMjUwMDg3ZmUzODRhYzU2MjhhNTJcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSomcmVzcG9uc2UtY29udGVudC10eXBlPSomdXNlcl9pZD1wdWJsaWMmWC1YZXQtQ2FzLVVpZD1wdWJsaWMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkVwb2NoVGltZSI6MTc5MDMxODYyOX19fV19&Signature=MEYCIQCqQy7PO56L33i3lcb1UUNloyu%7EyxghVFE9u5mmAb21PgIhALFaSkuiCt%7EoVx2HYQ66G7YtZ8CCSPV-QqFt256QYD-s&Key-Pair-Id=01KXEF4KZ1B6FV465MAWR4M21F&Hash-Algorithm=SHA256
Resolving us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)... 136.110.234.240
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|136.110.234.240|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2176768976 (2.0G) [application/zip]
Saving to: ‘glove.840B.300d.zip’

glove.840B.300d.zip 100%[===================>]   2.03G   115MB/s    in 18s

2026-09-25 05:44:07 (117 MB/s) - ‘glove.840B.300d.zip’ saved [2176768976/2176768976]

In [3]:
# 模型解压
zip_file = "/kaggle/working/glove.840B.300d.zip"  # 存放多个 zip 的文件夹
output_dir = "/kaggle/working/"  
with zipfile.ZipFile(zip_file, "r") as zip_ref:
        # 解压到统一的目标文件夹（如果想按文件名单独建文件夹，可用下面的方法）
        zip_ref.extractall(output_dir)

print("done!")

done!

In [4]:
import os
import gensim

# 1. 定义路径
input_file = "/kaggle/working/glove.840B.300d.txt"
output_file = "/kaggle/working/glove.840B.300d.gensim.txt"

def convert_glove_to_gensim_safe(infile, outfile, expected_dim=300):
    print("开始清洗并转换 GloVe 文件（自动跳过损坏行）...")
    valid_count = 0
    temp_file = outfile + ".tmp"
    
    # 第一遍：过滤异常行并写入临时文件，同时统计有效词数
    with open(infile, 'r', encoding='utf-8', errors='ignore') as fin, \
         open(temp_file, 'w', encoding='utf-8') as fout:
        
        for line in fin:
            parts = line.strip().split(' ')
            # 校验倒数 300 列是否能够全部正确解析为浮点数
            if len(parts) >= expected_dim + 1:
                try:
                    [float(x) for x in parts[-expected_dim:]]
                    fout.write(line)
                    valid_count += 1
                except ValueError:
                    continue  # 跳过会导致 ValueError 的损坏行

    print(f"清洗完成！共保留 {valid_count} 条有效词向量。正在添加 Header 标头...")

    # 第二遍：写入符合 Gensim 要求的首行 Header (总词数 维度)
    with open(temp_file, 'r', encoding='utf-8') as fin, \
         open(outfile, 'w', encoding='utf-8') as fout:
        fout.write(f"{valid_count} {expected_dim}\n")
        for line in fin:
            fout.write(line)
            
    # 清理临时文件
    if os.path.exists(temp_file):
        os.remove(temp_file)
        
    print(f"转换成功！生成目标文件：{outfile}")

# 2. 执行安全转换
convert_glove_to_gensim_safe(input_file, output_file)

# 3. 正常加载清洗后的模型
print("正在加载清洗后的 Gensim 模型...")
wvmodel = gensim.models.KeyedVectors.load_word2vec_format(
    output_file, 
    binary=False, 
    encoding='utf-8'
)

print("模型成功加载至内存！就可以继续进行后续的向量计算了。")

开始清洗并转换 GloVe 文件（自动跳过损坏行）...
清洗完成！共保留 2196009 条有效词向量。正在添加 Header 标头...
转换成功！生成目标文件：/kaggle/working/glove.840B.300d.gensim.txt
正在加载清洗后的 Gensim 模型...

WARNING:gensim.models.keyedvectors:duplicate word '����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������' in word2vec file, ignoring all but first

模型成功加载至内存！就可以继续进行后续的向量计算了。

In [5]:
import logging
import os
import re
import sys
from itertools import chain

import gensim
import pandas as pd
import torch
from bs4 import BeautifulSoup
 
from sklearn.model_selection import train_test_split

import pickle

embed_size = 300
max_len = 512

# Read data from files
train = pd.read_csv("/kaggle/working/labeledTrainData.tsv", header=0,
                    delimiter="\t", quoting=3)
test = pd.read_csv("/kaggle/working/testData.tsv", header=0,
                   delimiter="\t", quoting=3)
unlabeled_train = pd.read_csv("/kaggle/working/unlabeledTrainData.tsv", header=0,
                              delimiter="\t", quoting=3)


def review_to_wordlist(review, remove_stopwords=False):
    # Function to convert a document to a sequence of words,
    # optionally removing stop words.  Returns a list of words.
    #
    # 1. Remove HTML
    review_text = BeautifulSoup(review, "lxml").get_text()
    #
    # 2. Remove non-letters
    review_text = re.sub("[^a-zA-Z]", " ", review_text)
    #
    # 3. Convert words to lower case and split them
    words = review_text.lower().split()
    #
    # 4. Optionally remove stop words (false by default)
    # if remove_stopwords:
    #     stops = set(stopwords.words("english"))
    #     words = [w for w in words if not w in stops]
    #
    # 5. Return a list of words
    return (words)


def encode_samples(tokenized_samples):
    features = []
    for sample in tokenized_samples:
        feature = []
        for token in sample:
            if token in word_to_idx:
                feature.append(word_to_idx[token])
            else:
                feature.append(0)
        features.append(feature)
    return features


def pad_samples(features, maxlen=max_len, PAD=0):
    padded_features = []
    for feature in features:
        if len(feature) >= maxlen:
            padded_feature = feature[:maxlen]
        else:
            padded_feature = feature
            while len(padded_feature) < maxlen:
                padded_feature.append(PAD)
        padded_features.append(padded_feature)
    return padded_features


if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)

    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info("running %s" % ''.join(sys.argv))

    clean_train_reviews, train_labels = [], []
    for i, review in enumerate(train["review"]):
        clean_train_reviews.append(review_to_wordlist(review, remove_stopwords=False))
        train_labels.append(train["sentiment"][i])

    clean_test_reviews = []
    for review in test["review"]:
        clean_test_reviews.append(review_to_wordlist(review, remove_stopwords=False))

    vocab = set(chain(*clean_train_reviews)) | set(chain(*clean_test_reviews))
    vocab_size = len(vocab)

    train_reviews, val_reviews, train_labels, val_labels = train_test_split(clean_train_reviews, train_labels,
                                                                            test_size=0.2, random_state=0)

    wvmodel = gensim.models.KeyedVectors.load_word2vec_format("/kaggle/working/glove.840B.300d.gensim.txt",
                                                              binary=False, encoding='utf-8')

    word_to_idx = {word: i + 1 for i, word in enumerate(vocab)}
    word_to_idx['<unk>'] = 0
    idx_to_word = {i + 1: word for i, word in enumerate(vocab)}
    idx_to_word[0] = '<unk>'

    train_features = torch.tensor(pad_samples(encode_samples(train_reviews)))
    val_features = torch.tensor(pad_samples(encode_samples(val_reviews)))
    test_features = torch.tensor(pad_samples(encode_samples(clean_test_reviews)))

    train_labels = torch.tensor(train_labels)
    val_labels = torch.tensor(val_labels)

    weight = torch.zeros(vocab_size + 1, embed_size)
    for i in range(len(wvmodel.index_to_key)):
        try:
            index = word_to_idx[wvmodel.index_to_key[i]]
            print(i)
        except:
            continue
        weight[index, :] = torch.from_numpy(wvmodel.get_vector(
            idx_to_word[word_to_idx[wvmodel.index_to_key[i]]]))

    # 1. 定义保存路径
    pickle_file = 'pickle/imdb_glove.pickle3'

    # 2. 自动创建父文件夹（如果文件夹不存在则自动新建，已存在则忽略）
    os.makedirs(os.path.dirname(pickle_file), exist_ok=True)
    
    # 创建结果保存文件夹 
    output_dir = "./result"
    os.makedirs(output_dir, exist_ok=True)
    
    
    pickle.dump(
        [train_features, train_labels, val_features, val_labels, test_features, weight, word_to_idx, idx_to_word, vocab],
        open(pickle_file, 'wb'))
    print('data dumped!')

INFO:colab_kernel_launcher.py:running /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py-f/root/.local/share/jupyter/runtime/kernel-f31ffe25-0c60-43f3-9afc-fd67af15430a.json
INFO:gensim.models.keyedvectors:loading projection weights from /kaggle/working/glove.840B.300d.gensim.txt
WARNING:gensim.models.keyedvectors:duplicate word '����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������' in word2vec file, ignoring all but first
INFO:gensim.utils:KeyedVectors lifecycle event {'msg': 'loaded (2196009, 300) matrix of type float32 from /kaggle/working/glove.840B.300d.gensim.txt', 'binary': False, 'encoding': 'utf-8', 'datetime': '2026-09-25T06:20:07.898590', 'gensim': '4.4.0', 'python': '3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]', 'platform': 'Linux-6.12.90+-x86_64-with-glibc2.35', 'event': 'load_word2vec_format'}

2
3
4
5
6
7
10
11
15
17
18
19
21
23
24
25
26
27
28
29
30
31
32
34
35
38
39
41
42
43
44
45
47
48
49
50
51
52
53
56
58
59
60
61
64
67
68
69
70
73
74
75
77
78
81
82
83
84
85
86
87
88
89
91
92
94
96
97
99
100
101
102
104
105
106
107
108
110
111
112
113
114
116
117
118
119
120
121
122
123
125
126
127
129
132
133
134
135
137
138
139
140
141
142
143
145
149
151
152
153
154
155
156
157
158
159
161
162
164
166
169
170
171
173
175
176
177
179
180
182
183
184
185
186
187
189
191
192
194
195
196
203
204
205
207
209
210
211
212
213
214
216
218
220
226
227
228
229
230
232
233
234
235
238
239
243
244
245
246
247
248
249
251
252
253
254
257
258
259
261
263
264
265
266
267
268
269
270
271
273
275
276
277
278
279
281
282
283
284
285
287
288
290
291
292
294
296
297
298
301
304
305
306
308
309
310
311
312
313
314
316
317
320
321
322
323
324
326
328
329
330
331
332
333
334
335
336
338
339
341
342
343
344
345
348
349
351
352
353
354
355
357
358
359
360
362
364
365
366
368
370
371
372
373
375
377
381
382
385
387
388
389
390
392
393
394
395
396
397
398
399
400
401
402
404
405
406
408
409
411
413
414
415
416
417
419
421
423
426
427
428
430
434
435
436
437
438
439
441
442
443
445
446
447
448
450
451
454
455
456
458
459
462
464
465
466
467
468
470
471
472
473
474
476
477
478
480
481
483
484
485
486
487
488
490
491
493
495
497
498
499
501
504
505
507
509
510
514
515
518
521
522
523
524
525
526
528
529
530
534
536
537
539
540
541
542
543
544
545
547
549
550
551
552
554
555
556
557
558
560
561
562
563
564
566
568
570
572
574
575
576
578
580
581
582
583
584
586
588
589
590
591
592
594
597
598
599
600
601
602
603
606
607
608
611
612
613
614
615
616
617
619
620
621
622
623
625
626
627
628
629
630
632
633
635
636
637
638
639
641
643
644
646
647
652
653
655
656
657
658
659
661
662
665
667
669
671
674
676
677
678
679
680
682
683
684
685
686
687
688
690
691
694
695
697
698
700
701
702
703
704
705
707
709
710
712
714
715
716
717
718
721
722
723
724
725
727
728
729
731
732
734
736
737
739
740
742
746
747
748
750
751
752
753
754
755
756
757
759
761
762
763
765
766
767
768
769
770
771
772
774
775
776
777
778
779
780
781
782
785
786
788
789
791
794
795
796
798
799
800
801
804
807
808
809
810
811
812
813
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
838
839
840
841
842
843
845
847
848
849
851
852
853
854
855
856
857
858
859
860
861
863
864
865
866
867
868
869
870
872
875
876
877
878
880
882
883
884
885
886
887
889
890
891
892
894
895
896
897
898
899
900
901
902
903
906
907
908
910
912
913
914
917
918
919
921
923
924
926
927
932
933
934
935
936
937
938
939
940
942
943
944
945
946
947
948
950
951
952
956
957
958
959
961
962
963
964
966
967
968
969
970
971
972
974
976
977
978
979
980
982
984
988
989
990
991
992
995
997
1003
1004
1005
1006
1007
1008
1009
1011
1013
1014
1015
1016
1018
1020
1022
1023
1024
1025
1026
1029
1030
1031
1032
1033
1035
1036
1039
1040
1042
1044
1045
1048
1050
1051
1054
1055
1056
1057
1059
1060
1063
1065
1066
1067
1068
1069
1071
1074
1077
1078
1079
1080
1081
1083
1084
1086
1089
1090
1091
1092
1093
1094
1096
1097
1098
1099
1100
1102
1103
1104
1107
1108
1109
1111
1114
1115
1117
1118
1119
1120
1122
1123
1125
1126
1127
1128
1129
1130
1132
1134
1135
1136
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1164
1168
1170
1172
1173
1174
1176
1178
1179
1180
1182
1183
1184
1186
1188
1189
1191
1192
1193
1195
1197
1198
1201
1202
1204
1205
1209
1210
1211
1213
1214
1215
1218
1219
1220
1222
1224
1225
1226
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1241
1242
1243
1244
1245
1246
1250
1251
1252
1254
1255
1257
1258
1259
1260
1261
1262
1263
1264
1267
1268
1270
1271
1277
1279
1280
1283
1284
1285
1286
1287
1288
1289
1290
1294
1295
1296
1300
1301
1303
1304
1305
1306
1308
1309
1310
1312
1315
1317
1318
1319
1320
1322
1323
1324
1325
1327
1328
1329
1331
1332
1333
1335
1337
1338
1339
1341
1342
1343
1347
1348
1350
1351
1353
1354
1355
1356
1359
1361
1362
1363
1364
1365
1370
1371
1374
1375
1376
1377
1378
1380
1382
1384
1387
1388
1389
1390
1391
1392
1394
1395
1397
1398
1399
1402
1403
1405
1407
1408
1410
1411
1412
1413
1416
1418
1420
1421
1422
1423
1424
1427
1432
1434
1435
1437
1439
1440
1442
1445
1451
1452
1455
1456
1458
1459
1460
1462
1464
1467
1468
1470
1472
1475
1478
1479
1480
1484
1485
1487
1488
1489
1490
1491
1492
1494
1496
1497
1498
1500
1502
1503
1504
1508
1509
1511
1512
1513
1515
1518
1520
1521
1523
1524
1527
1529
1532
1534
1535
1537
1538
1539
1540
1541
1542
1544
1545
1546
1547
1548
1550
1553
1554
1555
1556
1557
1558
1561
1562
1564
1565
1566
1568
1569
1570
1573
1574
1575
1576
1577
1578
1580
1581
1582
1583
1584
1585
1586
1587
1589
1590
1591
1592
1593
1594
1597
1598
1599
1602
1603
1604
1605
1608
1609
1610
1611
1614
1615
1617
1618
1620
1622
1624
1626
1628
1629
1631
1632
1633
1634
1637
1638
1639
1640
1641
1642
1643
1644
1645
1648
1650
1651
1652
1653
1654
1656
1658
1659
1662
1663
1664
1665
1666
1667
1668
1669
1671
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1685
1688
1692
1693
1694
1695
1696
1698
1700
1702
1704
1705
1707
1708
1709
1710
1711
1712
1713
1716
1717
1718
1719
1721
1722
1723
1725
1728
1729
1730
1731
1732
1733
1734
1735
1737
1740
1741
1742
1743
1744
1746
1747
1748
1749
1751
1752
1754
1756
1757
1758
1761
1762
1763
1764
1765
1766
1767
1768
1772
1773
1775
1776
1778
1780
1781
1783
1784
1786
1787
1789
1791
1792
1794
1795
1798
1799
1801
1803
1804
1805
1807
1808
1809
1810
1812
1814
1816
1817
1818
1819
1820
1821
1825
1826
1827
1829
1830
1832
1834
1835
1838
1840
1843
1844
1846
1847
1848
1850
1851
1855
1856
1857
1859
1862
1864
1866
1868
1869
1872
1874
1875
1879
1880
1881
1882
1883
1884
1886
1887
1888
1889
1890
1892
1893
1894
1895
1896
1897
1901
1904
1905
1907
1908
1910
1912
1916
1917
1920
1921
1922
1923
1925
1929
1931
1932
1933
1934
1937
1938
1939
1940
1941
1943
1944
1945
1946
1947
1948
1949
1950
1951
1954
1955
1956
1958
1959
1960
1961
1962
1963
1965
1966
1967
1968
1971
1973
1974
1975
1976
1977
1978
1980
1981
1983
1984
1985
1986
1987
1989
1990
1993
1994
1995
1997
1998
2000
2001
2004
2007
2008
2009
2010
2011
2012
2015
2016
2017
2018
2019
2022
2024
2026
2028
2029
2032
2033
2034
2035
2036
2037
2038
2039
2041
2043
2045
2047
2048
2049
2050
2052
2054
2056
2057
2059
2060
2061
2062
2065
2066
2067
2069
2070
2073
2075
2077
2079
2080
2081
2082
2083
2085
2086
2089
2092
2093
2095
2099
2100
2101
2104
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2117
2120
2124
2125
2126
2128
2132
2133
2134
2135
2137
2139
2140
2141
2142
2145
2147
2148
2149
2150
2151
2152
2158
2160
2161
2163
2164
2165
2167
2168
2169
2170
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2187
2190
2191
2192
2193
2194
2195
2196
2198
2199
2200
2203
2205
2206
2208
2209
2211
2214
2215
2216
2217
2218
2219
2220
2221
2222
2224
2226
2229
2230
2232
2234
2235
2236
2238
2243
2245
2247
2248
2250
2251
2253
2257
2258
2259
2260
2261
2262
2263
2265
2266
2267
2268
2269
2270
2272
2273
2275
2276
2277
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2294
2298
2299
2302
2303
2305
2307
2308
2310
2311
2312
2314
2316
2319
2320
2321
2324
2326
2327
2330
2331
2333
2334
2335
2336
2338
2339
2341
2343
2344
2345
2346
2347
2348
2349
2352
2353
2354
2355
2356
2357
2359
2360
2361
2362
2363
2367
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2381
2382
2385
2387
2388
2389
2390
2396
2398
2399
2401
2402
2404
2405
2408
2409
2410
2411
2415
2418
2419
2422
2423
2424
2426
2427
2429
2433
2434
2435
2436
2437
2438
2441
2442
2443
2446
2447
2448
2449
2453
2454
2455
2456
2458
2459
2460
2461
2464
2465
2469
2470
2471
2472
2474
2475
2476
2477
2478
2479
2480
2481
2483
2487
2488
2491
2492
2495
2496
2498
2500
2504
2506
2509
2511
2512
2513
2514
2515
2519
2520
2521
2522
2523
2524
2526
2527
2528
2530
2531
2532
2533
2534
2535
2537
2538
2539
2542
2543
2545
2546
2547
2548
2550
2551
2553
2554
2555
2556
2560
2561
2562
2565
2567
2571
2572
2574
2576
2578
2585
2587
2589
2590
2592
2594
2595
2597
2598
2600
2601
2605
2606
2608
2610
2611
2613
2614
2615
2616
2619
2621
2623
2624
2625
2626
2627
2628
2630
2631
2633
2634
2635
2636
2637
2638
2639
2640
2641
2643
2644
2645
2647
2651
2652
2653
2654
2655
2656
2657
2660
2662
2664
2665
2668
2669
2670
2671
2673
2674
2677
2679
2680
2681
2682
2683
2685
2688
2691
2695
2697
2698
2699
2700
2703
2704
2705
2706
2707
2710
2711
2713
2714
2715
2716
2717
2718
2719
2720
2721
2723
2724
2726
2727
2728
2729
2732
2733
2734
2735
2736
2738
2739
2741
2743
2745
2747
2748
2749
2750
2754
2756
2758
2759
2760
2763
2764
2765
2766
2767
2769
2770
2772
2773
2774
2775
2776
2777
2778
2779
2781
2782
2783
2784
2785
2786
2788
2790
2791
2793
2794
2795
2796
2800
2801
2802
2804
2806
2807
2810
2811
2812
2815
2818
2819
2820
2821
2822
2824
2826
2828
2829
2831
2833
2834
2835
2836
2839
2840
2841
2843
2844
2845
2847
2850
2851
2856
2857
2858
2859
2860
2861
2863
2864
2866
2869
2870
2871
2872
2873
2874
2877
2879
2881
2884
2886
2887
2888
2890
2891
2892
2893
2898
2899
2900
2903
2904
2908
2909
2911
2913
2914
2915
2916
2920
2921
2922
2923
2924
2926
2927
2928
2929
2930
2934
2935
2936
2937
2938
2939
2943
2944
2945
2947
2948
2951
2954
2956
2958
2966
2967
2968
2970
2971
2972
2974
2975
2977
2978
2979
2980
2981
2982
2984
2985
2986
2987
2988
2989
2992
2993
2994
2995
2997
2999
3001
3002
3003
3004
3006
3007
3010
3011
3015
3016
3018
3019
3022
3024
3025
3026
3027
3028
3030
3032
3034
3035
3036
3037
3039
3040
3041
3042
3043
3044
3048
3049
3051
3052
3053
3054
3057
3058
3059
3061
3063
3065
3067
3068
3070
3073
3076
3078
3079
3080
3081
3083
3085
3088
3091
3093
3094
3097
3099
3100
3101
3103
3105
3106
3109
3110
3111
3112
3113
3114
3117
3119
3120
3124
3126
3129
3130
3131
3135
3136
3137
3138
3139
3142
3143
3145
3146
3148
3149
3150
3152
3154
3155
3156
3157
3158
3161
3162
3163
3165
3167
3168
3175
3177
3179
3180
3181
3183
3184
3185
3186
3190
3191
3192
3193
3195
3196
3198
3199
3203
3204
3207
3208
3209
3212
3213
3214
3215
3216
3217
3218
3220
3222
3224
3228
3229
3230
3232
3233
3234
3235
3236
3237
3238
3239
3240
3242
3243
3244
3245
3247
3248
3250
3251
3252
3253
3254
3256
3258
3260
3262
3264
3267
3268
3269
3270
3271
3272
3273
3275
3276
3279
3281
3284
3286
3287
3289
3290
3291
3294
3295
3297
3298
3299
3300
3302
3306
3308
3309
3311
3312
3317
3319
3320
3324
3325
3326
3327
3328
3329
3330
3331
3332
3334
3335
3336
3337
3338
3339
3345
3347
3349
3350
3351
3352
3354
3355
3356
3357
3358
3361
3362
3363
3366
3373
3375
3376
3378
3380
3381
3383
3384
3385
3386
3390
3391
3392
3395
3397
3398
3399
3400
3401
3404
3405
3408
3411
3412
3416
3418
3419
3420
3421
3422
3423
3424
3425
3426
3427
3431
3435
3437
3438
3439
3441
3443
3447
3448
3449
3450
3452
3453
3454
3456
3457
3458
3459
3463
3464
3467
3468
3469
3470
3473
3474
3477
3478
3481
3484
3485
3489
3490
3491
3496
3497
3498
3499
3500
3501
3503
3505
3507
3508
3511
3512
3513
3514
3515
3516
3517
3518
3520
3521
3523
3525
3526
3527
3528
3529
3532
3533
3538
3539
3542
3543
3545
3546
3547
3549
3550
3551
3552
3553
3554
3555
3556
3559
3565
3566
3567
3574
3575
3576
3577
3579
3580
3581
3583
3585
3588
3590
3592
3594
3596
3598
3599
3601
3602
3603
3606
3608
3609
3612
3614
3615
3616
3617
3618
3619
3620
3621
3622
3625
3627
3629
3631
3632
3633
3636
3637
3640
3643
3644
3645
3649
3653
3654
3655
3657
3658
3659
3660
3663
3665
3667
3668
3669
3670
3671
3672
3674
3675
3677
3679
3684
3685
3687
3689
3692
3696
3699
3700
3701
3702
3703
3707
3709
3711
3714
3715
3716
3717
3722
3724
3726
3727
3728
3729
3735
3737
3739
3740
3741
3742
3743
3745
3746
3747
3749
3750
3751
3752
3753
3754
3757
3758
3760
3762
3764
3765
3766
3767
3769
3770
3771
3772
3773
3774
3777
3779
3780
3784
3785
3786
3788
3789
3791
3793
3795
3796
3797
3798
3800
3801
3803
3804
3805
3806
3809
3810
3811
3812
3813
3814
3815
3816
3817
3818
3819
3820
3822
3823
3824
3826
3827
3828
3829
3830
3832
3833
3836
3839
3840
3842
3846
3847
3848
3849
3850
3851
3856
3857
3859
3860
3861
3862
3864
3865
3866
3867
3868
3869
3870
3871
3872
3874
3875
3877
3879
3881
3883
3884
3886
3888
3890
3892
3894
3895
3896
3898
3900
3901
3903
3905
3906
3907
3909
3910
3911
3913
3915
3917
3918
3919
3920
3921
3922
3925
3926
3927
3928
3929
3930
3931
3932
3934
3935
3936
3937
3939
3940
3941
3944
3946
3948
3949
3951
3954
3955
3956
3957
3958
3959
3960
3961
3962
3965
3969
3970
3971
3972
3973
3974
3975
3978
3979
3980
3981
3982
3983
3984
3985
3990
3992
3995
3996
3998
3999
4000
4002
4004
4005
4006
4009
4011
4013
4014
4018
4020
4021
4022
4023
4025
4027
4028
4029
4032
4033
4035
4036
4037
4042
4043
4044
4048
4052
4053
4055
4056
4058
4059
4061
4063
4067
4068
4069
4070
4071
4073
4074
4075
4077
4078
4079
4081
4082
4083
4086
4087
4090
4091
4093
4094
4095
4097
4099
4100
4101
4102
4107
4109
4110
4111
4112
4117
4119
4121
4122
4123
4124
4125
4127
4128
4129
4130
4131
4132
4134
4135
4137
4138
4139
4144
4146
4147
4148
4149
4151
4154
4155
4157
4159
4162
4164
4165
4168
4170
4172
4173
4177
4178
4179
4180
4181
4182
4183
4185
4188
4189
4191
4192
4193
4194
4199
4200
4201
4202
4204
4205
4207
4209
4210
4213
4214
4215
4218
4220
4221
4223
4224
4225
4227
4228
4229
4230
4232
4233
4234
4235
4238
4240
4241
4243
4244
4251
4252
4253
4254
4255
4256
4258
4259
4260
4261
4262
4264
4266
4268
4270
4272
4275
4276
4277
4280
4282
4283
4287
4290
4295
4296
4297
4298
4299
4300
4301
4302
4303
4304
4305
4308
4309
4310
4311
4312
4314
4315
4317
4318
4322
4326
4331
4332
4334
4336
4339
4340
4341
4345
4348
4350
4351
4352
4353
4354
4356
4357
4358
4361
4365
4366
4367
4371
4372
4373
4374
4376
4380
4381
4382
4384
4387
4388
4389
4391
4392
4394
4395
4397
4398
4400
4402
4403
4405
4406
4407
4408
4409
4411
4412
4413
4414
4417
4418
4420
4421
4422
4424
4427
4428
4430
4431
4432
4433
4434
4435
4436
4437
4438
4441
4444
4445
4446
4449
4450
4451
4453
4454
4458
4461
4462
4463
4464
4466
4467
4469
4471
4472
4475
4476
4477
4478
4479
4480
4481
4482
4483
4484
4487
4488
4490
4494
4495
4497
4498
4499
4500
4501
4503
4506
4507
4508
4510
4511
4512
4513
4514
4515
4516
4517
4520
4521
4522
4525
4526
4527
4528
4529
4530
4531
4532
4533
4534
4536
4538
4540
4542
4543
4545
4547
4549
4551
4555
4556
4559
4562
4564
4565
4566
4567
4568
4570
4571
4572
4574
4575
4576
4577
4579
4580
4581
4582
4583
4584
4585
4586
4587
4588
4590
4591
4592
4594
4595
4597
4598
4601
4603
4604
4605
4606
4610
4611
4612
4614
4617
4619
4620
4622
4623
4626
4627
4629
4632
4633
4637
4638
4640
4642
4644
4645
4646
4647
4649
4653
4654
4655
4657
4659
4661
4663
4671
4673
4674
4675
4676
4677
4678
4680
4681
4683
4685
4686
4687
4688
4689
4690
4692
4693
4694
4695
4697
4699
4705
4707
4708
4710
4711
4713
4714
4715
4718
4719
4720
4724
4725
4727
4728
4729
4730
4731
4732
4734
4736
4737
4738
4741
4742
4743
4746
4748
4749
4752
4753
4757
4758
4760
4761
4762
4764
4765
4766
4769
4770
4771
4772
4773
4775
4777
4779
4780
4781
4782
4783
4784
4789
4791
4792
4794
4799
4800
4801
4809
4810
4811
4813
4815
4820
4826
4828
4829
4831
4832
4833
4834
4835
4836
4838
4839
4840
4844
4846
4848
4850
4854
4855
4860
4861
4862
4863
4864
4865
4866
4867
4868
4870
4871
4872
4874
4875
4876
4877
4878
4882
4883
4885
4887
4890
4892
4893
4895
4896
4899
4900
4902
4903
4905
4907
4908
4909
4910
4913
4915
4916
4917
4918
4922
4925
4926
4927
4928
4929
4930
4932
4933
4934
4935
4937
4940
4942
4943
4946
4948
4951
4953
4954
4955
4956
4957
4959
4960
4961
4963
4965
4966
4967
4968
4969
4972
4974
4975
4976
4978
4980
4982
4983
4984
4985
4986
4987
4989
4994
4995
4997
4998
4999
5001
5002
5003
5005
5006
5007
5008
5009
5010
5011
5012
5013
5014
5015
5018
5020
5021
5022
5023
5024
5026
5027
5030
5031
5032
5034
5035
5038
5039
5042
5043
5046
5048
5050
5051
5053
5054
5055
5056
5058
5060
5062
5063
5064
5065
5067
5069
5070
5072
5075
5079
5081
5082
5083
5084
5086
5087
5088
5089
5091
5092
5093
5096
5097
5099
5100
5103
5104
5107
5112
5113
5116
5119
5123
5124
5126
5127
5129
5130
5131
5133
5134
5135
5136
5141
5142
5143
5144
5147
5148
5149
5151
5155
5156
5160
5166
5167
5169
5170
5172
5174
5175
5178
5185
5186
5188
5189
5190
5191
5192
5193
5198
5202
5203
5204
5206
5207
5209
5210
5211
5213
5214
5215
5217
5218
5221
5224
5231
5232
5233
5235
5238
5242
5244
5245
5248
5250
5251
5254
5256
5259
5260
5262
5263
5264
5266
5268
5269
5270
5271
5272
5274
5277
5278
5280
5281
5283
5284
5287
5288
5289
5297
5298
5300
5301
5302
5303
5306
5308
5310
5311
5312
5314
5315
5317
5318
5320
5321
5324
5326
5328
5329
5330
5331
5333
5335
5337
5338
5339
5341
5342
5344
5345
5347
5349
5350
5355
5357
5358
5360
5361
5362
5363
5364
5367
5370
5371
5372
5373
5374
5375
5376
5377
5379
5380
5381
5382
5383
5384
5385
5386
5387
5391
5393
5395
5396
5397
5398
5399
5401
5402
5407
5408
5409
5410
5413
5415
5416
5417
5422
5425
5426
5429
5431
5434
5435
5436
5438
5442
5443
5449
5451
5452
5453
5454
5455
5457
5458
5459
5462
5463
5466
5467
5468
5469
5470
5471
5472
5473
5475
5476
5477
5478
5480
5484
5485
5486
5487
5489
5491
5492
5499
5500
5501
5502
5504
5506
5507
5509
5510
5513
5524
5525
5528
5530
5531
5532
5533
5534
5535
5537
5540
5541
5543
5545
5546
5548
5550
5551
5552
5553
5554
5556
5557
5558
5560
5561
5566
5567
5571
5572
5573
5574
5576
5578
5579
5581
5583
5584
5586
5588
5590
5591
5592
5595
5597
5598
5599
5601
5605
5607
5609
5611
5612
5613
5614
5615
5616
5617
5619
5620
5621
5622
5624
5626
5627
5629
5631
5632
5633
5636
5638
5639
5640
5641
5643
5644
5646
5648
5651
5652
5653
5654
5655
5656
5658
5659
5660
5662
5665
5667
5668
5671
5673
5674
5678
5684
5685
5688
5689
5690
5692
5694
5695
5696
5697
5699
5700
5701
5702
5703
5704
5705
5707
5708
5711
5713
5714
5715
5724
5726
5729
5731
5732
5733
5735
5736
5737
5740
5741
5742
5743
5745
5746
5749
5754
5756
5758
5759
5763
5764
5765
5767
5771
5773
5780
5783
5784
5786
5788
5789
5790
5793
5794
5796
5798
5802
5803
5805
5806
5809
5810
5813
5814
5815
5817
5819
5821
5822
5824
5826
5827
5828
5830
5831
5833
5834
5835
5836
5838
5839
5840
5846
5848
5849
5850
5851
5852
5853
5856
5858
5859
5860
5861
5862
5864
5865
5866
5867
5868
5869
5873
5874
5875
5876
5877
5880
5881
5883
5885
5887
5888
5889
5890
5891
5892
5893
5896
5898
5900
5905
5906
5907
5908
5911
5912
5913
5915
5917
5918
5919
5920
5921
5925
5931
5933
5935
5936
5937
5938
5941
5948
5950
5951
5952
5953
5956
5957
5958
5959
5960
5961
5962
5964
5965
5968
5969
5972
5974
5976
5977
5983
5984
5985
5987
5989
5990
5991
5993
5994
5995
5997
5999
6000
6001
6002
6003
6005
6006
6007
6010
6011
6013
6018
6020
6022
6023
6027
6031
6032
6033
6034
6035
6037
6038
6039
6045
6048
6050
6051
6052
6054
6059
6060
6063
6065
6066
6069
6071
6076
6078
6080
6081
6088
6090
6092
6095
6098
6102
6103
6104
6105
6106
6107
6108
6109
6110
6111
6113
6114
6117
6120
6121
6124
6125
6127
6128
6129
6130
6131
6132
6135
6137
6138
6139
6140
6141
6142
6144
6145
6146
6153
6154
6155
6156
6159
6160
6161
6163
6164
6165
6166
6167
6168
6171
6172
6177
6178
6179
6181
6182
6183
6184
6185
6186
6187
6189
6192
6193
6194
6197
6198
6199
6200
6203
6204
6205
6206
6207
6208
6210
6213
6215
6216
6218
6220
6222
6224
6225
6229
6230
6231
6236
6237
6238
6239
6241
6242
6243
6244
6249
6250
6252
6253
6254
6255
6257
6258
6259
6261
6263
6265
6266
6267
6268
6274
6275
6276
6277
6278
6279
6281
6283
6287
6288
6289
6292
6294
6295
6299
6300
6301
6304
6305
6306
6307
6308
6309
6311
6313
6315
6316
6317
6319
6320
6321
6325
6326
6327
6330
6331
6333
6335
6336
6338
6340
6343
6346
6347
6348
6351
6353
6354
6355
6356
6358
6360
6361
6363
6365
6366
6367
6368
6369
6371
6373
6376
6377
6378
6379
6380
6383
6385
6386
6388
6389
6390
6397
6398
6400
6402
6403
6404
6408
6409
6410
6411
6412
6413
6414
6415
6416
6417
6418
6419
6421
6422
6423
6426
6427
6429
6430
6431
6434
6435
6438
6439
6440
6441
6442
6443
6447
6452
6453
6454
6455
6456
6457
6460
6462
6463
6465
6466
6467
6468
6469
6470
6471
6472
6474
6475
6477
6478
6479
6480
6482
6483
6486
6489
6490
6491
6492
6493
6494
6495
6496
6497
6499
6500
6502
6505
6506
6510
6511
6512
6514
6516
6517
6518
6519
6521
6522
6523
6524
6525
6526
6528
6529
6531
6533
6535
6536
6537
6539
6540
6541
6543
6544
6545
6546
6547
6548
6549
6553
6556
6558
6559
6560
6561
6563
6566
6567
6571
6573
6574
6575
6576
6577
6578
6579
6580
6583
6584
6585
6586
6587
6588
6589
6590
6592
6593
6594
6595
6597
6598
6599
6602
6605
6606
6608
6609
6610
6611
6613
6616
6618
6620
6622
6624
6626
6627
6629
6630
6631
6632
6635
6637
6638
6641
6643
6647
6648
6651
6652
6653
6654
6655

/tmp/ipykernel_59/1309776149.py:121: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  weight[index, :] = torch.from_numpy(wvmodel.get_vector(

18251
18252
18254
18257
18260
18261
18263
18264
18265
18274
18277
18278
18284
18285
18286
18290
18295
18296
18297
18299
18300
18301
18307
18308
18309
18315
18319
18320
18323
18327
18329
18332
18333
18338
18339
18345
18346
18347
18348
18350
18352
18354
18355
18358
18363
18364
18366
18367
18370
18371
18372
18373
18384
18387
18391
18394
18395
18397
18398
18401
18402
18403
18404
18405
18407
18409
18412
18413
18416
18417
18418
18420
18421
18423
18425
18427
18428
18429
18431
18435
18442
18446
18449
18451
18452
18453
18454
18458
18463
18464
18466
18472
18473
18474
18475
18481
18482
18483
18485
18491
18492
18496
18497
18498
18502
18506
18507
18508
18509
18510
18512
18516
18517
18525
18528
18531
18537
18538
18540
18541
18544
18547
18548
18550
18557
18559
18562
18563
18564
18577
18581
18583
18584
18585
18588
18591
18597
18599
18600
18602
18604
18609
18612
18613
18614
18615
18621
18622
18625
18627
18628
18631
18633
18635
18636
18638
18639
18642
18646
18647
18649
18651
18653
18655
18656
18657
18659
18662
18663
18666
18672
18674
18680
18681
18682
18683
18686
18687
18688
18689
18693
18696
18697
18699
18703
18706
18707
18710
18724
18726
18727
18728
18730
18731
18732
18734
18736
18737
18740
18741
18742
18743
18744
18747
18748
18750
18751
18753
18754
18762
18767
18770
18771
18773
18775
18776
18777
18779
18780
18783
18786
18787
18788
18790
18791
18792
18794
18800
18803
18806
18809
18812
18813
18816
18817
18818
18820
18821
18823
18827
18828
18829
18832
18837
18841
18842
18847
18848
18851
18853
18855
18856
18857
18858
18860
18861
18863
18866
18867
18875
18877
18884
18885
18887
18891
18893
18894
18896
18897
18898
18900
18901
18903
18906
18908
18909
18910
18912
18914
18916
18917
18918
18919
18920
18924
18927
18929
18930
18931
18934
18935
18944
18945
18948
18950
18952
18953
18955
18956
18957
18958
18959
18962
18965
18966
18968
18969
18971
18972
18973
18975
18977
18978
18982
18983
18985
18986
18987
18989
18991
18993
18997
18998
18999
19002
19003
19004
19010
19011
19012
19013
19015
19018
19019
19022
19025
19026
19027
19029
19032
19033
19034
19038
19039
19041
19042
19046
19047
19048
19050
19056
19060
19062
19063
19064
19065
19066
19067
19068
19073
19075
19079
19080
19082
19084
19086
19089
19090
19091
19092
19094
19097
19098
19099
19102
19104
19106
19107
19108
19109
19110
19112
19114
19116
19119
19120
19124
19126
19127
19128
19130
19132
19135
19138
19141
19142
19144
19145
19147
19151
19154
19157
19158
19165
19167
19169
19170
19172
19175
19179
19180
19183
19188
19189
19191
19199
19202
19203
19205
19207
19212
19215
19217
19221
19223
19225
19227
19230
19231
19233
19234
19236
19237
19238
19240
19246
19255
19256
19257
19258
19259
19264
19266
19269
19271
19273
19274
19276
19278
19283
19284
19286
19289
19291
19295
19296
19298
19299
19300
19311
19315
19317
19318
19319
19322
19323
19324
19325
19327
19328
19329
19333
19334
19338
19339
19341
19342
19343
19348
19351
19352
19355
19357
19361
19365
19367
19368
19369
19375
19377
19381
19382
19385
19387
19388
19390
19391
19395
19398
19400
19401
19403
19405
19408
19409
19411
19415
19417
19422
19425
19427
19428
19429
19438
19439
19443
19447
19450
19452
19460
19461
19462
19463
19464
19465
19466
19468
19469
19470
19472
19473
19474
19476
19477
19479
19481
19483
19485
19486
19487
19490
19491
19493
19495
19497
19499
19500
19505
19506
19507
19509
19510
19511
19512
19515
19517
19520
19526
19528
19531
19535
19536
19540
19544
19548
19549
19550
19552
19555
19559
19562
19565
19568
19569
19573
19575
19579
19583
19585
19586
19587
19594
19595
19601
19603
19605
19606
19608
19609
19610
19611
19612
19613
19614
19618
19621
19622
19623
19630
19631
19633
19635
19636
19637
19642
19643
19644
19645
19646
19650
19652
19653
19656
19658
19661
19662
19664
19665
19666
19667
19668
19670
19674
19675
19676
19677
19681
19683
19684
19687
19690
19691
19693
19697
19704
19707
19708
19710
19713
19714
19715
19716
19720
19723
19726
19727
19732
19743
19744
19746
19748
19751
19752
19753
19754
19755
19758
19760
19764
19766
19767
19768
19769
19772
19773
19775
19776
19777
19780
19783
19787
19796
19799
19800
19801
19803
19805
19806
19807
19808
19809
19813
19816
19818
19820
19822
19823
19828
19833
19835
19836
19839
19842
19848
19852
19854
19855
19862
19866
19867
19870
19873
19877
19880
19882
19883
19884
19887
19888
19890
19892
19895
19896
19898
19899
19904
19906
19910
19912
19914
19915
19917
19918
19920
19922
19924
19926
19929
19930
19932
19938
19943
19944
19945
19947
19950
19951
19953
19957
19960
19961
19964
19965
19969
19970
19971
19974
19977
19979
19980
19986
19988
19990
19991
19992
19994
19995
19996
19997
19998
19999
20000
20001
20002
20003
20006
20010
20011
20013
20016
20017
20018
20023
20025
20026
20027
20030
20032
20033
20034
20035
20036
20037
20038
20040
20041
20043
20044
20046
20047
20048
20051
20053
20055
20056
20057
20058
20059
20060
20061
20062
20066
20068
20069
20070
20071
20072
20074
20076
20081
20082
20083
20087
20090
20096
20097
20102
20103
20107
20110
20113
20114
20115
20116
20121
20123
20124
20125
20126
20127
20128
20129
20132
20134
20137
20139
20142
20143
20148
20150
20151
20152
20153
20154
20155
20157
20165
20166
20167
20169
20172
20173
20175
20176
20177
20178
20179
20183
20186
20188
20189
20190
20191
20193
20194
20198
20199
20200
20203
20205
20206
20210
20211
20214
20215
20216
20218
20219
20223
20224
20227
20229
20233
20234
20236
20237
20239
20243
20247
20248
20257
20258
20262
20264
20268
20270
20273
20274
20278
20279
20281
20282
20284
20285
20288
20292
20293
20298
20300
20301
20302
20303
20304
20306
20307
20310
20312
20314
20319
20322
20324
20330
20331
20333
20334
20340
20344
20345
20346
20347
20356
20357
20362
20364
20366
20367
20369
20373
20375
20377
20382
20388
20393
20396
20398
20399
20400
20403
20406
20408
20411
20413
20425
20428
20432
20433
20438
20440
20442
20443
20445
20448
20454
20458
20459
20463
20464
20465
20466
20467
20468
20469
20471
20473
20476
20480
20481
20482
20487
20490
20491
20497
20503
20506
20507
20508
20514
20518
20519
20520
20522
20527
20530
20533
20538
20540
20541
20545
20547
20554
20555
20557
20561
20563
20565
20566
20567
20569
20573
20574
20575
20578
20579
20581
20585
20587
20589
20592
20596
20597
20598
20603
20604
20609
20610
20611
20613
20614
20615
20616
20618
20620
20622
20626
20627
20629
20631
20632
20636
20637
20638
20639
20640
20641
20643
20648
20649
20650
20652
20657
20658
20662
20663
20664
20665
20668
20669
20671
20672
20673
20674
20675
20677
20678
20680
20683
20686
20688
20689
20691
20692
20697
20701
20702
20703
20704
20705
20706
20709
20716
20717
20719
20722
20723
20725
20727
20728
20730
20731
20732
20734
20735
20739
20741
20745
20746
20747
20748
20750
20752
20754
20757
20761
20762
20769
20772
20775
20776
20779
20780
20783
20785
20787
20788
20789
20795
20798
20800
20801
20803
20804
20805
20806
20809
20812
20815
20819
20820
20821
20823
20824
20825
20826
20827
20828
20830
20832
20834
20835
20838
20840
20843
20846
20848
20853
20857
20859
20861
20862
20863
20864
20870
20881
20888
20890
20891
20893
20895
20896
20898
20899
20906
20908
20910
20914
20919
20923
20928
20929
20930
20933
20936
20938
20939
20948
20953
20959
20960
20961
20964
20967
20968
20969
20970
20971
20972
20973
20976
20977
20980
20981
20986
20987
20990
20997
20998
20999
21001
21002
21003
21005
21007
21008
21012
21013
21014
21016
21020
21021
21024
21028
21029
21030
21031
21032
21034
21035
21036
21037
21038
21040
21042
21043
21044
21046
21050
21052
21054
21055
21056
21059
21060
21062
21064
21068
21070
21072
21073
21075
21076
21080
21082
21083
21085
21087
21089
21090
21091
21096
21097
21098
21099
21102
21106
21108
21109
21112
21114
21117
21118
21120
21122
21124
21125
21127
21129
21134
21136
21137
21140
21141
21142
21143
21145
21146
21147
21149
21154
21157
21158
21164
21166
21167
21169
21170
21173
21175
21177
21179
21180
21182
21184
21186
21188
21189
21191
21194
21196
21198
21203
21204
21206
21210
21212
21214
21216
21217
21219
21220
21221
21228
21230
21234
21236
21240
21242
21247
21249
21250
21252
21253
21260
21264
21270
21274
21275
21276
21283
21287
21288
21289
21290
21294
21295
21299
21300
21301
21304
21305
21308
21309
21310
21317
21319
21323
21325
21326
21331
21334
21337
21338
21341
21342
21346
21348
21350
21353
21354
21355
21359
21363
21364
21367
21368
21371
21372
21373
21374
21376
21377
21382
21383
21385
21387
21389
21391
21396
21397
21400
21404
21409
21414
21415
21417
21418
21420
21422
21425
21428
21432
21433
21440
21444
21447
21448
21449
21450
21454
21455
21456
21458
21461
21464
21466
21467
21469
21470
21472
21473
21476
21479
21481
21484
21488
21493
21498
21500
21501
21502
21503
21509
21511
21518
21519
21520
21522
21525
21526
21528
21530
21532
21533
21539
21540
21545
21557
21559
21560
21562
21564
21568
21569
21570
21572
21577
21578
21579
21583
21586
21587
21590
21594
21595
21598
21600
21601
21602
21604
21609
21611
21612
21613
21614
21615
21617
21618
21619
21622
21623
21624
21629
21632
21633
21635
21639
21643
21648
21650
21651
21652
21656
21657
21658
21661
21662
21664
21667
21668
21671
21675
21678
21679
21684
21687
21691
21693
21694
21697
21700
21702
21703
21704
21708
21709
21717
21719
21722
21723
21726
21732
21736
21738
21740
21741
21742
21745
21747
21748
21749
21752
21754
21756
21757
21758
21759
21760
21762
21764
21765
21768
21769
21770
21771
21772
21777
21781
21783
21785
21786
21788
21791
21793
21797
21802
21805
21806
21807
21809
21815
21818
21821
21828
21829
21830
21832
21835
21838
21839
21840
21841
21843
21844
21852
21853
21854
21856
21861
21864
21867
21872
21875
21876
21877
21879
21881
21882
21883
21891
21892
21893
21894
21897
21898
21902
21904
21906
21907
21910
21913
21914
21915
21917
21921
21922
21925
21928
21929
21931
21932
21933
21934
21938
21941
21942
21947
21948
21952
21954
21955
21957
21961
21962
21966
21967
21968
21970
21973
21975
21977
21979
21980
21981
21984
21985
21986
21988
21989
21990
21993
21997
22000
22002
22005
22006
22009
22010
22012
22014
22015
22017
22020
22022
22027
22033
22036
22037
22038
22040
22042
22043
22044
22058
22059
22062
22064
22069
22070
22074
22075
22081
22082
22085
22087
22092
22094
22096
22097
22098
22099
22101
22104
22105
22106
22122
22127
22129
22130
22132
22136
22137
22138
22142
22144
22145
22146
22151
22152
22153
22166
22174
22178
22179
22180
22181
22182
22183
22190
22193
22194
22197
22198
22199
22202
22204
22205
22207
22210
22216
22218
22219
22220
22221
22225
22226
22233
22234
22235
22241
22245
22246
22247
22249
22250
22252
22254
22256
22258
22261
22265
22267
22269
22270
22271
22273
22274
22277
22278
22279
22280
22286
22288
22290
22292
22293
22294
22295
22296
22298
22301
22304
22306
22308
22309
22311
22314
22315
22316
22322
22324
22327
22328
22330
22333
22334
22336
22337
22340
22341
22342
22343
22345
22349
22354
22355
22359
22360
22361
22363
22364
22365
22366
22369
22371
22375
22384
22387
22388
22390
22391
22392
22393
22396
22400
22402
22403
22406
22407
22410
22411
22417
22418
22419
22422
22428
22429
22432
22434
22435
22438
22441
22442
22445
22446
22447
22452
22462
22466
22467
22469
22470
22471
22476
22478
22482
22483
22485
22486
22488
22489
22495
22496
22498
22499
22501
22506
22507
22509
22511
22512
22516
22518
22520
22523
22525
22526
22528
22531
22534
22535
22539
22540
22541
22543
22547
22548
22551
22557
22559
22562
22564
22567
22569
22571
22573
22574
22579
22581
22585
22588
22589
22590
22591
22594
22597
22598
22601
22602
22606
22607
22613
22614
22615
22618
22621
22623
22624
22625
22629
22633
22634
22637
22640
22642
22643
22647
22649
22650
22652
22653
22656
22657
22660
22670
22673
22675
22676
22677
22678
22683
22684
22687
22688
22689
22692
22693
22696
22697
22699
22702
22710
22711
22712
22714
22721
22724
22725
22727
22729
22730
22732
22733
22734
22737
22742
22743
22745
22750
22752
22753
22755
22756
22758
22759
22764
22769
22770
22776
22780
22782
22783
22789
22791
22798
22800
22801
22802
22804
22808
22809
22810
22812
22813
22817
22820
22827
22829
22832
22833
22840
22845
22848
22853
22856
22857
22860
22862
22863
22865
22867
22868
22871
22872
22874
22878
22879
22881
22883
22884
22886
22887
22889
22896
22897
22898
22899
22902
22906
22907
22909
22910
22911
22913
22916
22920
22922
22923
22929
22930
22932
22933
22935
22941
22943
22946
22949
22951
22954
22955
22958
22971
22972
22977
22978
22985
22986
22987
22988
22989
22991
22993
22995
22997
22999
23000
23001
23003
23005
23006
23007
23009
23011
23014
23015
23017
23019
23022
23023
23025
23026
23027
23028
23029
23032
23034
23037
23043
23045
23046
23048
23052
23054
23055
23056
23057
23060
23061
23064
23069
23070
23071
23073
23074
23075
23076
23077
23079
23080
23081
23082
23083
23091
23098
23099
23100
23108
23109
23110
23116
23117
23123
23125
23126
23127
23128
23132
23133
23134
23135
23138
23140
23141
23144
23148
23149
23151
23152
23154
23156
23157
23172
23174
23175
23177
23179
23180
23181
23182
23183
23185
23187
23190
23193
23195
23196
23198
23204
23205
23206
23207
23209
23215
23216
23217
23218
23220
23223
23224
23225
23226
23229
23232
23233
23235
23237
23238
23241
23243
23247
23249
23250
23253
23255
23257
23258
23260
23261
23264
23265
23272
23274
23277
23278
23280
23285
23288
23289
23298
23299
23300
23301
23303
23304
23305
23306
23308
23310
23311
23312
23313
23315
23316
23317
23319
23320
23322
23325
23331
23335
23338
23339
23341
23342
23343
23344
23345
23346
23347
23348
23349
23352
23355
23357
23358
23360
23365
23367
23368
23371
23372
23374
23375
23380
23386
23387
23389
23391
23396
23397
23409
23411
23412
23414
23415
23419
23421
23422
23426
23428
23429
23433
23435
23436
23438
23439
23441
23445
23449
23453
23458
23460
23463
23466
23469
23470
23472
23475
23476
23477
23478
23480
23482
23484
23486
23490
23491
23492
23493
23495
23501
23505
23506
23507
23509
23510
23511
23512
23513
23515
23517
23520
23526
23529
23531
23532
23537
23540
23541
23542
23544
23546
23547
23548
23553
23557
23558
23559
23562
23563
23564
23565
23570
23573
23574
23575
23576
23577
23580
23582
23583
23584
23586
23589
23596
23602
23604
23605
23607
23609
23612
23613
23616
23617
23618
23620
23621
23622
23627
23630
23631
23635
23636
23638
23639
23643
23644
23646
23647
23651
23657
23660
23664
23665
23667
23669
23674
23678
23685
23688
23689
23690
23691
23692
23694
23706
23707
23708
23709
23711
23715
23716
23718
23720
23721
23722
23724
23725
23726
23727
23731
23734
23737
23739
23740
23743
23744
23745
23746
23747
23748
23749
23753
23756
23758
23760
23761
23767
23768
23769
23774
23776
23777
23778
23780
23781
23784
23785
23792
23799
23800
23802
23803
23808
23814
23816
23817
23820
23823
23827
23828
23830
23832
23833
23835
23836
23838
23839
23843
23844
23850
23851
23854
23855
23861
23862
23864
23870
23872
23873
23874
23881
23884
23887
23888
23897
23901
23903
23905
23909
23910
23911
23914
23915
23916
23923
23924
23927
23928
23931
23932
23933
23934
23935
23936
23941
23943
23945
23946
23948
23958
23961
23962
23964
23969
23974
23976
23982
23984
23985
23986
23988
23993
23996
23997
23998
24001
24004
24005
24006
24010
24012
24016
24018
24026
24030
24031
24032
24033
24036
24037
24038
24040
24046
24048
24053
24054
24055
24056
24059
24060
24062
24064
24065
24066
24069
24070
24071
24072
24074
24076
24077
24079
24080
24084
24085
24090
24094
24095
24100
24104
24106
24108
24110
24111
24112
24113
24115
24118
24121
24122
24123
24124
24126
24129
24130
24133
24134
24135
24138
24140
24143
24147
24150
24151
24153
24154
24155
24157
24159
24160
24161
24162
24165
24166
24169
24172
24180
24183
24186
24190
24195
24196
24198
24200
24203
24204
24205
24206
24207
24210
24211
24214
24216
24221
24222
24225
24228
24229
24230
24232
24240
24241
24242
24243
24245
24247
24249
24252
24253
24255
24256
24257
24258
24260
24262
24265
24267
24269
24270
24275
24276
24282
24286
24288
24289
24290
24291
24292
24294
24302
24303
24304
24307
24311
24312
24313
24316
24317
24320
24324
24325
24329
24331
24332
24333
24334
24337
24345
24348
24353
24356
24357
24359
24360
24361
24362
24364
24365
24367
24369
24370
24371
24372
24376
24377
24380
24384
24386
24388
24390
24391
24395
24397
24398
24402
24403
24406
24408
24409
24411
24413
24414
24416
24417
24418
24420
24422
24423
24424
24425
24428
24431
24433
24435
24436
24442
24447
24449
24450
24455
24462
24464
24465
24469
24470
24471
24472
24474
24477
24478
24480
24482
24487
24489
24490
24493
24494
24495
24501
24503
24504
24507
24509
24510
24513
24514
24518
24520
24521
24525
24527
24530
24531
24534
24535
24536
24539
24547
24548
24556
24559
24560
24561
24566
24567
24568
24571
24581
24582
24583
24586
24587
24588
24589
24590
24591
24593
24595
24598
24599
24607
24611
24613
24620
24621
24622
24625
24629
24631
24632
24638
24641
24642
24643
24647
24653
24655
24656
24659
24661
24662
24663
24665
24670
24671
24676
24678
24679
24684
24685
24687
24689
24690
24691
24693
24695
24699
24701
24703
24705
24706
24707
24709
24712
24715
24716
24718
24719
24722
24723
24724
24725
24727
24729
24734
24735
24736
24737
24743
24744
24746
24749
24753
24755
24758
24759
24760
24761
24763
24764
24765
24767
24768
24770
24772
24773
24774
24775
24776
24778
24780
24782
24783
24786
24787
24789
24792
24795
24796
24799
24801
24802
24803
24805
24807
24809
24811
24814
24815
24818
24819
24821
24823
24827
24828
24829
24832
24833
24834
24838
24841
24845
24846
24847
24850
24852
24858
24859
24862
24864
24865
24870
24871
24873
24874
24875
24877
24878
24884
24886
24890
24893
24894
24895
24902
24903
24905
24906
24907
24908
24912
24913
24914
24915
24917
24920
24921
24924
24930
24934
24935
24936
24940
24943
24945
24948
24950
24951
24953
24954
24956
24957
24963
24968
24971
24972
24973
24977
24978
24979
24980
24982
24984
24985
24987
24988
24989
24991
24993
24996
24999
25002
25003
25004
25006
25007
25008
25022
25023
25025
25036
25038
25039
25040
25041
25044
25047
25052
25055
25056
25057
25058
25060
25063
25066
25067
25069
25072
25075
25076
25077
25081
25083
25084
25085
25086
25089
25093
25098
25106
25109
25110
25113
25115
25116
25118
25124
25125
25126
25128
25129
25132
25136
25137
25139
25140
25144
25145
25149
25150
25151
25153
25154
25156
25161
25168
25169
25174
25176
25180
25182
25188
25190
25193
25194
25200
25202
25203
25205
25213
25214
25217
25218
25219
25220
25221
25223
25224
25225
25228
25229
25230
25232
25233
25234
25236
25238
25239
25243
25245
25247
25250
25252
25259
25262
25263
25264
25266
25269
25270
25273
25275
25277
25279
25282
25283
25284
25285
25289
25290
25293
25294
25301
25303
25308
25310
25316
25318
25320
25321
25322
25326
25329
25337
25338
25341
25342
25345
25346
25347
25348
25349
25351
25353
25359
25360
25362
25363
25364
25365
25366
25368
25369
25371
25378
25379
25382
25386
25387
25389
25390
25391
25393
25395
25398
25403
25404
25405
25409
25410
25413
25416
25419
25424
25425
25427
25428
25429
25430
25441
25444
25448
25450
25452
25455
25460
25461
25462
25463
25464
25465
25471
25473
25477
25478
25482
25486
25489
25493
25498
25499
25506
25507
25508
25514
25519
25524
25526
25527
25529
25533
25534
25535
25537
25545
25546
25548
25549
25550
25554
25560
25561
25563
25564
25566
25567
25569
25575
25576
25577
25579
25580
25581
25582
25584
25585
25590
25593
25595
25596
25598
25601
25605
25606
25610
25611
25612
25614
25616
25619
25621
25625
25628
25630
25632
25633
25635
25636
25642
25649
25651
25652
25654
25657
25658
25662
25668
25670
25671
25674
25676
25677
25679
25681
25686
25687
25688
25691
25693
25694
25696
25700
25702
25704
25705
25706
25707
25708
25710
25713
25714
25716
25718
25720
25723
25724
25725
25726
25731
25732
25733
25734
25735
25737
25740
25743
25744
25745
25747
25749
25756
25759
25761
25765
25768
25769
25771
25777
25778
25780
25785
25787
25788
25791
25799
25801
25802
25805
25806
25807
25808
25810
25814
25818
25821
25824
25826
25828
25829
25831
25832
25834
25839
25844
25845
25850
25856
25858
25859
25860
25863
25865
25866
25868
25874
25876
25878
25879
25882
25883
25884
25888
25891
25892
25893
25895
25896
25900
25902
25903
25904
25905
25908
25910
25913
25914
25916
25917
25918
25919
25920
25925
25926
25928
25931
25934
25935
25938
25940
25946
25949
25951
25954
25957
25961
25965
25966
25967
25968
25970
25974
25976
25977
25979
25982
25984
25985
25987
25991
25993
25999
26004
26005
26009
26012
26016
26019
26025
26026
26030
26031
26033
26034
26037

## imdb-cnn

In [ ]:
import logging
import os
import sys
import pickle
import time

import pandas as pd
import torch
from torch import nn
from torch.nn import functional as F
from torch import optim
from torch.autograd import Variable
from tqdm import tqdm


from sklearn.metrics import accuracy_score


test = pd.read_csv("/kaggle/working/testData.tsv", header=0, delimiter="\t", quoting=3)

num_epochs = 30
embed_size = 300
num_filter = 128
filter_size = 3
bidirectional = True
batch_size = 64
labels = 2
lr = 0.1
device = torch.device('cuda:0')
use_gpu = True


class SentimentNet(nn.Module):
    def __init__(self, embed_size, num_filter, filter_size, weight, labels, use_gpu, **kwargs):
        super(SentimentNet, self).__init__(**kwargs)
        self.use_gpu = use_gpu
        self.embedding = nn.Embedding.from_pretrained(weight)
        self.embedding.weight.requires_grad = False

        self.conv1d = nn.Conv1d(embed_size, num_filter, filter_size, padding=1)
        self.activate = F.relu
        self.decoder = nn.Linear(num_filter, labels)


    def forward(self, inputs):
        embeddings = self.embedding(inputs)

        convolution = self.activate(self.conv1d(embeddings.permute([0, 2, 1])))
        pooling = F.max_pool1d(convolution, kernel_size=convolution.shape[2])

        outputs = self.decoder(pooling.squeeze(dim=2))
        # print(outputs)
        return outputs


if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)

    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info(r"running %s" % ''.join(sys.argv))

    logging.info('loading data...')
    pickle_file = "/kaggle/working/pickle/imdb_glove.pickle3"
    [train_features, train_labels, val_features, val_labels, test_features, weight, word_to_idx, idx_to_word,
            vocab] = pickle.load(open(pickle_file, 'rb'))
    logging.info('data loaded!')

    net = SentimentNet(embed_size=embed_size, num_filter=num_filter, filter_size=filter_size,
                       weight=weight, labels=labels, use_gpu=use_gpu)
    net.to(device)
    loss_function = nn.CrossEntropyLoss()
    optimizer = optim.SGD(net.parameters(), lr=lr)

    train_set = torch.utils.data.TensorDataset(train_features, train_labels)
    val_set = torch.utils.data.TensorDataset(val_features, val_labels)
    test_set = torch.utils.data.TensorDataset(test_features, )

    train_iter = torch.utils.data.DataLoader(train_set, batch_size=batch_size, shuffle=True)
    val_iter = torch.utils.data.DataLoader(val_set, batch_size=batch_size, shuffle=False)
    test_iter = torch.utils.data.DataLoader(test_set, batch_size=batch_size, shuffle=False)

    for epoch in range(num_epochs):
        start = time.time()
        train_loss, val_losses = 0, 0
        train_acc, val_acc = 0, 0
        n, m = 0, 0
        with tqdm(total=len(train_iter), desc='Epoch %d' % epoch) as pbar:
            for feature, label in train_iter:
                n += 1
                net.zero_grad()
                feature = Variable(feature.cuda())
                label = Variable(label.cuda())
                score = net(feature)
                loss = loss_function(score, label)
                loss.backward()
                optimizer.step()
                train_acc += accuracy_score(torch.argmax(score.cpu().data,
                                                         dim=1), label.cpu())
                train_loss += loss

                pbar.set_postfix({'epoch': '%d' % (epoch),
                                  'train loss': '%.4f' % (train_loss.data / n),
                                  'train acc': '%.2f' % (train_acc / n)
                                  })
                pbar.update(1)

            with torch.no_grad():
                for val_feature, val_label in val_iter:
                    m += 1
                    val_feature = val_feature.cuda()
                    val_label = val_label.cuda()
                    val_score = net(val_feature)
                    val_loss = loss_function(val_score, val_label)
                    val_acc += accuracy_score(torch.argmax(val_score.cpu().data, dim=1), val_label.cpu())
                    val_losses += val_loss
            end = time.time()
            runtime = end - start
            pbar.set_postfix({'epoch': '%d' % (epoch),
                              'train loss': '%.4f' % (train_loss.data / n),
                              'train acc': '%.2f' % (train_acc / n),
                              'val loss': '%.4f' % (val_losses.data / m),
                              'val acc': '%.2f' % (val_acc / m),
                              'time': '%.2f' % (runtime)})

            # tqdm.write('{epoch: %d, train loss: %.4f, train acc: %.2f, val loss: %.4f, val acc: %.2f, time: %.2f}' %
            #       (epoch, train_loss.data / n, train_acc / n, val_losses.data / m, val_acc / m, runtime))

    test_pred = []
    with torch.no_grad():
        with tqdm(total=len(test_iter), desc='Prediction') as pbar:
            for test_feature, in test_iter:
                test_feature = test_feature.cuda()
                test_score = net(test_feature)
                # test_pred.extent
                test_pred.extend(torch.argmax(test_score.cpu().data, dim=1).numpy().tolist())

                pbar.update(1)

    result_output = pd.DataFrame(data={"id": test["id"], "sentiment": test_pred})
    
    result_output.to_csv("./result/cnn.csv", index=False, quoting=3)
    logging.info('result saved!')

## imdb-cnnlstm

In [ ]:
import logging
import os
import sys
import pickle
import time

import pandas as pd
import torch
from torch import nn
from torch.nn import functional as F
from torch import optim
from torch.autograd import Variable
from tqdm import tqdm


from sklearn.metrics import accuracy_score


test = pd.read_csv("/kaggle/working/testData.tsv", header=0, delimiter="\t", quoting=3)

num_epochs = 30
max_len = 512

embed_size = 300
num_filter = 128
filter_size = 2
pooling_size = 2

num_hiddens = 64
num_layers = 2

bidirectional = True
batch_size = 64
labels = 2
lr = 0.05
device = torch.device('cuda:0')
use_gpu = True


class SentimentNet(nn.Module):
    def __init__(self, embed_size, num_filter, filter_size, num_hiddens, num_layers, bidirectional, weight, labels, use_gpu, **kwargs):
        super(SentimentNet, self).__init__(**kwargs)
        self.embed_size = embed_size
        self.num_filter = num_filter
        self.filter_size = filter_size
        self.num_hiddens = num_hiddens
        self.num_layers = num_layers
        self.bidirectional = bidirectional
        self.labels = labels

        self.use_gpu = use_gpu

        self.embedding = nn.Embedding.from_pretrained(weight)
        self.embedding.weight.requires_grad = False

        self.conv1d = nn.Conv1d(self.embed_size, self.num_filter, self.filter_size, padding=1)
        self.activate = F.relu

        self.encoder = nn.LSTM(input_size=max_len//pooling_size, hidden_size=self.num_hiddens,
                              num_layers=self.num_layers, bidirectional=self.bidirectional,
                              dropout=0)

        if self.bidirectional:
            self.decoder = nn.Linear(num_hiddens * 4, labels)
        else:
            self.decoder = nn.Linear(num_hiddens * 2, labels)


    def forward(self, inputs):
        embeddings = self.embedding(inputs)

        # cnn
        convolution = self.activate(self.conv1d(embeddings.permute([0, 2, 1])))
        pooling = F.max_pool1d(convolution, kernel_size=pooling_size)

        # lstm (seq_len, batch_size, hidden_dim)
        states, hidden = self.encoder(pooling.permute([1, 0, 2]))
        encoding = torch.cat([states[0], states[-1]], dim=1)

        outputs = self.decoder(encoding)
        return outputs


if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)

    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info(r"running %s" % ''.join(sys.argv))

    logging.info('loading data...')
    pickle_file = "/kaggle/working/pickle/imdb_glove.pickle3"
    [train_features, train_labels, val_features, val_labels, test_features, weight, word_to_idx, idx_to_word,
            vocab] = pickle.load(open(pickle_file, 'rb'))
    logging.info('data loaded!')

    net = SentimentNet(embed_size=embed_size, num_filter=num_filter, filter_size=filter_size,
                       num_hiddens=num_hiddens, num_layers=num_layers, bidirectional=bidirectional,
                       weight=weight, labels=labels, use_gpu=use_gpu)
    net.to(device)
    loss_function = nn.CrossEntropyLoss()
    optimizer = optim.SGD(net.parameters(), lr=lr)

    train_set = torch.utils.data.TensorDataset(train_features, train_labels)
    val_set = torch.utils.data.TensorDataset(val_features, val_labels)
    test_set = torch.utils.data.TensorDataset(test_features, )

    train_iter = torch.utils.data.DataLoader(train_set, batch_size=batch_size, shuffle=True)
    val_iter = torch.utils.data.DataLoader(val_set, batch_size=batch_size, shuffle=False)
    test_iter = torch.utils.data.DataLoader(test_set, batch_size=batch_size, shuffle=False)


    for epoch in range(num_epochs):
        start = time.time()
        train_loss, val_losses = 0, 0
        train_acc, val_acc = 0, 0
        n, m = 0, 0
        with tqdm(total=len(train_iter), desc='Epoch %d' % epoch) as pbar:
            for feature, label in train_iter:
                n += 1
                net.zero_grad()
                feature = Variable(feature.cuda())
                label = Variable(label.cuda())
                score = net(feature)
                loss = loss_function(score, label)
                loss.backward()
                optimizer.step()
                train_acc += accuracy_score(torch.argmax(score.cpu().data,
                                                         dim=1), label.cpu())
                train_loss += loss

                pbar.set_postfix({'epoch': '%d' % (epoch),
                                  'train loss': '%.4f' % (train_loss.data / n),
                                  'train acc': '%.2f' % (train_acc / n)
                                  })
                pbar.update(1)

            with torch.no_grad():
                for val_feature, val_label in val_iter:
                    m += 1
                    val_feature = val_feature.cuda()
                    val_label = val_label.cuda()
                    val_score = net(val_feature)
                    val_loss = loss_function(val_score, val_label)
                    val_acc += accuracy_score(torch.argmax(val_score.cpu().data, dim=1), val_label.cpu())
                    val_losses += val_loss
            end = time.time()
            runtime = end - start
            pbar.set_postfix({'epoch': '%d' % (epoch),
                              'train loss': '%.4f' % (train_loss.data / n),
                              'train acc': '%.2f' % (train_acc / n),
                              'val loss': '%.4f' % (val_losses.data / m),
                              'val acc': '%.2f' % (val_acc / m),
                              'time': '%.2f' % (runtime)})

            # tqdm.write('{epoch: %d, train loss: %.4f, train acc: %.2f, val loss: %.4f, val acc: %.2f, time: %.2f}' %
            #       (epoch, train_loss.data / n, train_acc / n, val_losses.data / m, val_acc / m, runtime))

    test_pred = []
    with torch.no_grad():
        with tqdm(total=len(test_iter), desc='Prediction') as pbar:
            for test_feature, in test_iter:
                test_feature = test_feature.cuda()
                test_score = net(test_feature)
                # test_pred.extent
                test_pred.extend(torch.argmax(test_score.cpu().data, dim=1).numpy().tolist())

                pbar.update(1)

    result_output = pd.DataFrame(data={"id": test["id"], "sentiment": test_pred})
    result_output.to_csv("./result/cnn-lstm.csv", index=False, quoting=3)
    logging.info('result saved!')

## imdb-attention-lstm

In [ ]:
import logging
import os
import sys
import pickle
import time

import pandas as pd
import torch
from torch import nn
from torch import optim
from torch.nn import functional as F
from torch.autograd import Variable
from tqdm import tqdm

from sklearn.metrics import accuracy_score


test = pd.read_csv("/kaggle/working/testData.tsv", header=0, delimiter="\t", quoting=3)

num_epochs = 10
embed_size = 300
num_hiddens = 128
num_layers = 2
bidirectional = True
batch_size = 64
labels = 2
lr = 0.01
device = torch.device('cuda:0')
use_gpu = True


class Attention(nn.Module):
    def __init__(self, num_hiddens, bidirectional, **kwargs):
        super(Attention, self).__init__(**kwargs)
        self.num_hiddens = num_hiddens
        self.bidirectional = bidirectional

        # if bidirectional, then double the hidden dimensionality
        if self.bidirectional:
            self.w_omega = nn.Parameter(torch.Tensor(num_hiddens * 2, num_hiddens * 2))
            self.u_omega = nn.Parameter(torch.Tensor(num_hiddens * 2, 1))
        else:
            self.w_omega = nn.Parameter(torch.Tensor(num_hiddens, num_hiddens))
            self.u_omega = nn.Parameter(torch.Tensor(num_hiddens, 1))

        nn.init.uniform_(self.w_omega, -0.1, 0.1)
        nn.init.uniform_(self.u_omega, -0.1, 0.1)

    def forward(self, inputs):
        x = inputs
        u = torch.tanh(torch.matmul(x, self.w_omega))
        att = torch.matmul(u, self.u_omega)

        att_score = F.softmax(att, dim=1)
        outputs = x * att_score
        return outputs


class SentimentNet(nn.Module):
    def __init__(self, embed_size, num_hiddens, num_layers, bidirectional, weight, labels, use_gpu, **kwargs):
        super(SentimentNet, self).__init__(**kwargs)
        self.embed_size = embed_size
        self.num_hiddens = num_hiddens
        self.num_layers = num_layers
        self.use_gpu = use_gpu
        self.bidirectional = bidirectional
        self.embedding = nn.Embedding.from_pretrained(weight)
        self.embedding.weight.requires_grad = False
        self.encoder = nn.LSTM(input_size=self.embed_size, hidden_size=self.num_hiddens,
                               num_layers=self.num_layers, bidirectional=self.bidirectional,
                               dropout=0)
        self.attention = Attention(num_hiddens=self.num_hiddens, bidirectional=self.bidirectional)
        if self.bidirectional:
            self.decoder = nn.Linear(num_hiddens * 4, labels)
        else:
            self.decoder = nn.Linear(num_hiddens * 2, labels)

    def forward(self, inputs):
        embeddings = self.embedding(inputs)
        states, hidden = self.encoder(embeddings.permute(1, 0, 2))
        attention = self.attention(states)
        encoding = torch.cat([attention[0], attention[-1]], dim=1)
        outputs = self.decoder(encoding)
        # print(outputs)
        return outputs


if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)

    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info(r"running %s" % ''.join(sys.argv))

    logging.info('loading data...')
    pickle_file = "/kaggle/working/pickle/imdb_glove.pickle3"
    [train_features, train_labels, val_features, val_labels, test_features, weight, word_to_idx, idx_to_word,
            vocab] = pickle.load(open(pickle_file, 'rb'))
    logging.info('data loaded!')

    net = SentimentNet(embed_size=embed_size, num_hiddens=num_hiddens, num_layers=num_layers,
                       bidirectional=bidirectional, weight=weight,
                       labels=labels, use_gpu=use_gpu)
    net.to(device)
    loss_function = nn.CrossEntropyLoss()
    optimizer = optim.Adam(net.parameters(), lr=lr)

    train_set = torch.utils.data.TensorDataset(train_features, train_labels)
    val_set = torch.utils.data.TensorDataset(val_features, val_labels)
    test_set = torch.utils.data.TensorDataset(test_features, )

    train_iter = torch.utils.data.DataLoader(train_set, batch_size=batch_size, shuffle=True)
    val_iter = torch.utils.data.DataLoader(val_set, batch_size=batch_size, shuffle=False)
    test_iter = torch.utils.data.DataLoader(test_set, batch_size=batch_size, shuffle=False)

    for epoch in range(num_epochs):
        start = time.time()
        train_loss, val_losses = 0, 0
        train_acc, val_acc = 0, 0
        n, m = 0, 0
        with tqdm(total=len(train_iter), desc='Epoch %d' % epoch) as pbar:
            for feature, label in train_iter:
                n += 1
                net.zero_grad()
                feature = Variable(feature.cuda())
                label = Variable(label.cuda())
                score = net(feature)
                loss = loss_function(score, label)
                loss.backward()
                optimizer.step()
                train_acc += accuracy_score(torch.argmax(score.cpu().data,
                                                         dim=1), label.cpu())
                train_loss += loss

                pbar.set_postfix({'epoch': '%d' % (epoch),
                                  'train loss': '%.4f' % (train_loss.data / n),
                                  'train acc': '%.2f' % (train_acc / n)
                                  })
                pbar.update(1)

            with torch.no_grad():
                for val_feature, val_label in val_iter:
                    m += 1
                    val_feature = val_feature.cuda()
                    val_label = val_label.cuda()
                    val_score = net(val_feature)
                    val_loss = loss_function(val_score, val_label)
                    val_acc += accuracy_score(torch.argmax(val_score.cpu().data, dim=1), val_label.cpu())
                    val_losses += val_loss
            end = time.time()
            runtime = end - start
            pbar.set_postfix({'epoch': '%d' % (epoch),
                              'train loss': '%.4f' % (train_loss.data / n),
                              'train acc': '%.2f' % (train_acc / n),
                              'val loss': '%.4f' % (val_losses.data / m),
                              'val acc': '%.2f' % (val_acc / m),
                              'time': '%.2f' % (runtime)
                              })

            # tqdm.write('{epoch: %d, train loss: %.4f, train acc: %.2f, val loss: %.4f, val acc: %.2f, time: %.2f}' %
            #       (epoch, train_loss.data / n, train_acc / n, val_losses.data / m, val_acc / m, runtime))

    test_pred = []
    with torch.no_grad():
        with tqdm(total=len(test_iter), desc='Prediction') as pbar:
            for test_feature, in test_iter:
                test_feature = test_feature.cuda()
                test_score = net(test_feature)
                # test_pred.extent
                test_pred.extend(torch.argmax(test_score.cpu().data, dim=1).numpy().tolist())

                pbar.update(1)

    result_output = pd.DataFrame(data={"id": test["id"], "sentiment": test_pred})
    result_output.to_csv("./result/attention_lstm.csv", index=False, quoting=3)
    logging.info('result saved!')

## imdb-capsule-lstm

In [ ]:
import logging
import os
import sys
import pickle
import time

import pandas as pd
import torch
from torch import nn
from torch import optim
from torch.nn import functional as F
from torch.autograd import Variable
from tqdm import tqdm

from sklearn.metrics import accuracy_score

test = pd.read_csv("/kaggle/working/testData.tsv", header=0, delimiter="\t", quoting=3)

num_epochs = 15
embed_size = 300
num_hiddens = 128
num_layers = 2
bidirectional = True
batch_size = 64
labels = 2
lr = 0.01
device = torch.device('cuda:0')
use_gpu = True


class Capsule(nn.Module):
    def __init__(self, num_hiddens, bidirectional, num_capsule=5, dim_capsule=5, routings=4, **kwargs):
        super(Capsule, self).__init__(**kwargs)
        self.num_hiddens = num_hiddens
        self.bidirectional = bidirectional

        self.num_capsule = num_capsule
        self.dim_capsule = dim_capsule
        self.routings = routings
        self.activation = self.squash

        input_dim = self.num_hiddens * (2 if self.bidirectional else 1)
        self.W = nn.Parameter(
            nn.init.xavier_normal_(torch.empty(input_dim, self.num_capsule * self.dim_capsule)))

    def forward(self, inputs):
        u_hat_vecs = torch.matmul(inputs, self.W)
        batch_size = inputs.size(0)
        input_num_capsule = inputs.size(1)
        u_hat_vecs = u_hat_vecs.view((batch_size, input_num_capsule,
                                      self.num_capsule, self.dim_capsule))

        u_hat_vecs = u_hat_vecs.permute(
            0, 2, 1, 3).contiguous()  # (batch_size,num_capsule,input_num_capsule,dim_capsule)
        with torch.no_grad():
            b = torch.zeros_like(u_hat_vecs[:, :, :, 0])
        for i in range(self.routings):
            c = torch.nn.functional.softmax(b, dim=1)  # (batch_size,num_capsule,input_num_capsule)
            outputs = self.activation(torch.sum(c.unsqueeze(-1) * u_hat_vecs, dim=2))  # bij,bijk->bik
            if i < self.routings - 1:
                b = (torch.sum(outputs.unsqueeze(2) * u_hat_vecs, dim=-1))  # bik,bijk->bij
        return outputs  # (batch_size, num_capsule, dim_capsule)

    @staticmethod
    def squash(x, axis=-1):
        s_squared_norm = (x ** 2).sum(axis, keepdim=True)
        scale = torch.sqrt(s_squared_norm + 1e-7)
        return x / scale


class SentimentNet(nn.Module):
    def __init__(self, embed_size, num_hiddens, num_layers, bidirectional, weight, labels, use_gpu, **kwargs):
        super(SentimentNet, self).__init__(**kwargs)
        self.embed_size = embed_size
        self.num_hiddens = num_hiddens
        self.num_layers = num_layers
        self.use_gpu = use_gpu
        self.bidirectional = bidirectional
        self.embedding = nn.Embedding.from_pretrained(weight)
        self.embedding.weight.requires_grad = False
        self.encoder = nn.LSTM(input_size=self.embed_size, hidden_size=self.num_hiddens,
                               num_layers=self.num_layers, bidirectional=self.bidirectional,
                               dropout=0)
        # self.attention = Attention(num_hiddens=self.num_hiddens, bidirectional=self.bidirectional)
        self.capsule = Capsule(num_hiddens=self.num_hiddens, bidirectional=self.bidirectional)
        self.decoder = nn.Linear(self.capsule.num_capsule * self.capsule.dim_capsule, labels)

    def forward(self, inputs):
        embeddings = self.embedding(inputs)
        states, hidden = self.encoder(embeddings.permute(1, 0, 2))
        capsule = self.capsule(states.transpose(0, 1))
        encoding = capsule.flatten(start_dim=1)
        outputs = self.decoder(encoding)
        # print(outputs)
        return outputs


if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)

    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info(r"running %s" % ''.join(sys.argv))

    logging.info('loading data...')
    pickle_file = "/kaggle/working/pickle/imdb_glove.pickle3"
    [train_features, train_labels, val_features, val_labels, test_features, weight, word_to_idx, idx_to_word,
     vocab] = pickle.load(open(pickle_file, 'rb'))
    logging.info('data loaded!')

    net = SentimentNet(embed_size=embed_size, num_hiddens=num_hiddens, num_layers=num_layers,
                       bidirectional=bidirectional, weight=weight,
                       labels=labels, use_gpu=use_gpu)
    net.to(device)
    loss_function = nn.CrossEntropyLoss()
    optimizer = optim.Adam(net.parameters(), lr=lr)

    train_set = torch.utils.data.TensorDataset(train_features, train_labels)
    val_set = torch.utils.data.TensorDataset(val_features, val_labels)
    test_set = torch.utils.data.TensorDataset(test_features, )

    train_iter = torch.utils.data.DataLoader(train_set, batch_size=batch_size, shuffle=True)
    val_iter = torch.utils.data.DataLoader(val_set, batch_size=batch_size, shuffle=False)
    test_iter = torch.utils.data.DataLoader(test_set, batch_size=batch_size, shuffle=False)

    for epoch in range(num_epochs):
        start = time.time()
        train_loss, val_losses = 0, 0
        train_acc, val_acc = 0, 0
        n, m = 0, 0
        with tqdm(total=len(train_iter), desc='Epoch %d' % epoch) as pbar:
            for feature, label in train_iter:
                n += 1
                net.zero_grad()
                feature = Variable(feature.cuda())
                label = Variable(label.cuda())
                score = net(feature)
                loss = loss_function(score, label)
                loss.backward()
                optimizer.step()
                train_acc += accuracy_score(torch.argmax(score.cpu().data,
                                                         dim=1), label.cpu())
                train_loss += loss

                pbar.set_postfix({'epoch': '%d' % (epoch),
                                  'train loss': '%.4f' % (train_loss.data / n),
                                  'train acc': '%.2f' % (train_acc / n)
                                  })
                pbar.update(1)

            with torch.no_grad():
                for val_feature, val_label in val_iter:
                    m += 1
                    val_feature = val_feature.cuda()
                    val_label = val_label.cuda()
                    val_score = net(val_feature)
                    val_loss = loss_function(val_score, val_label)
                    val_acc += accuracy_score(torch.argmax(val_score.cpu().data, dim=1), val_label.cpu())
                    val_losses += val_loss
            end = time.time()
            runtime = end - start
            pbar.set_postfix({'epoch': '%d' % (epoch),
                              'train loss': '%.4f' % (train_loss.data / n),
                              'train acc': '%.2f' % (train_acc / n),
                              'val loss': '%.4f' % (val_losses.data / m),
                              'val acc': '%.2f' % (val_acc / m),
                              'time': '%.2f' % (runtime)
                              })

            # tqdm.write('{epoch: %d, train loss: %.4f, train acc: %.2f, val loss: %.4f, val acc: %.2f, time: %.2f}' %
            #       (epoch, train_loss.data / n, train_acc / n, val_losses.data / m, val_acc / m, runtime))

    test_pred = []
    with torch.no_grad():
        with tqdm(total=len(test_iter), desc='Prediction') as pbar:
            for test_feature, in test_iter:
                test_feature = test_feature.cuda()
                test_score = net(test_feature)
                # test_pred.extent
                test_pred.extend(torch.argmax(test_score.cpu().data, dim=1).numpy().tolist())

                pbar.update(1)

    result_output = pd.DataFrame(data={"id": test["id"], "sentiment": test_pred})
    result_output.to_csv("./result/capsule_lstm.csv", index=False, quoting=3)
    logging.info('result saved!')

## imdb-gru

In [ ]:
import logging
import os
import sys
import pickle
import time

import pandas as pd
import torch
from torch import nn
from torch import optim
from torch.autograd import Variable
from tqdm import tqdm

from sklearn.metrics import accuracy_score


test = pd.read_csv("/kaggle/working/testData.tsv", header=0, delimiter="\t", quoting=3)

num_epochs = 30
embed_size = 300
num_hiddens = 120
num_layers = 2
bidirectional = True
batch_size = 64
labels = 2
lr = 0.05
device = torch.device('cuda:0')
use_gpu = True


class SentimentNet(nn.Module):
    def __init__(self, embed_size, num_hiddens, num_layers, bidirectional, weight, labels, use_gpu, **kwargs):
        super(SentimentNet, self).__init__(**kwargs)
        self.num_hiddens = num_hiddens
        self.num_layers = num_layers
        self.use_gpu = use_gpu
        self.bidirectional = bidirectional
        self.embedding = nn.Embedding.from_pretrained(weight)
        self.embedding.weight.requires_grad = False
        self.encoder = nn.GRU(input_size=embed_size, hidden_size=self.num_hiddens,
                               num_layers=num_layers, bidirectional=self.bidirectional, dropout=0)
        if self.bidirectional:
            self.decoder = nn.Linear(num_hiddens * 4, labels)
        else:
            self.decoder = nn.Linear(num_hiddens * 2, labels)

    def forward(self, inputs):
        embeddings = self.embedding(inputs)
        states, hidden = self.encoder(embeddings.permute([1, 0, 2]))
        encoding = torch.cat([states[0], states[-1]], dim=1)
        outputs = self.decoder(encoding)
        # print(outputs)
        return outputs


if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)

    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info(r"running %s" % ''.join(sys.argv))

    logging.info('loading data...')
    pickle_file = "/kaggle/working/pickle/imdb_glove.pickle3"
    [train_features, train_labels, val_features, val_labels, test_features, weight, word_to_idx, idx_to_word,
            vocab] = pickle.load(open(pickle_file, 'rb'))
    logging.info('data loaded!')


    net = SentimentNet(embed_size=embed_size, num_hiddens=num_hiddens, num_layers=num_layers,
                       bidirectional=bidirectional, weight=weight,
                       labels=labels, use_gpu=use_gpu)
    net.to(device)
    loss_function = nn.CrossEntropyLoss()
    optimizer = optim.SGD(net.parameters(), lr=lr)

    train_set = torch.utils.data.TensorDataset(train_features, train_labels)
    val_set = torch.utils.data.TensorDataset(val_features, val_labels)
    test_set = torch.utils.data.TensorDataset(test_features, )

    train_iter = torch.utils.data.DataLoader(train_set, batch_size=batch_size, shuffle=True)
    val_iter = torch.utils.data.DataLoader(val_set, batch_size=batch_size, shuffle=False)
    test_iter = torch.utils.data.DataLoader(test_set, batch_size=batch_size, shuffle=False)

    for epoch in range(num_epochs):
        start = time.time()
        train_loss, val_losses = 0, 0
        train_acc, val_acc = 0, 0
        n, m = 0, 0
        with tqdm(total=len(train_iter), desc='Epoch %d' % epoch) as pbar:
            for feature, label in train_iter:
                n += 1
                net.zero_grad()
                feature = Variable(feature.cuda())
                label = Variable(label.cuda())
                score = net(feature)
                loss = loss_function(score, label)
                loss.backward()
                optimizer.step()
                train_acc += accuracy_score(torch.argmax(score.cpu().data,
                                                         dim=1), label.cpu())
                train_loss += loss

                pbar.set_postfix({'epoch': '%d' % (epoch),
                                  'train loss': '%.4f' % (train_loss.data / n),
                                  'train acc': '%.2f' % (train_acc / n)
                                  })
                pbar.update(1)

            with torch.no_grad():
                for val_feature, val_label in val_iter:
                    m += 1
                    val_feature = val_feature.cuda()
                    val_label = val_label.cuda()
                    val_score = net(val_feature)
                    val_loss = loss_function(val_score, val_label)
                    val_acc += accuracy_score(torch.argmax(val_score.cpu().data, dim=1), val_label.cpu())
                    val_losses += val_loss
            end = time.time()
            runtime = end - start
            pbar.set_postfix({'epoch': '%d' % (epoch),
                              'train loss': '%.4f' % (train_loss.data / n),
                              'train acc': '%.2f' % (train_acc / n),
                              'val loss': '%.4f' % (val_losses.data / m),
                              'val acc': '%.2f' % (val_acc / m),
                              'time': '%.2f' % (runtime)})

            # tqdm.write('{epoch: %d, train loss: %.4f, train acc: %.2f, val loss: %.4f, val acc: %.2f, time: %.2f}' %
            #       (epoch, train_loss.data / n, train_acc / n, val_losses.data / m, val_acc / m, runtime))

    test_pred = []
    with torch.no_grad():
        with tqdm(total=len(test_iter), desc='Prediction') as pbar:
            for test_feature, in test_iter:
                test_feature = test_feature.cuda()
                test_score = net(test_feature)
                # test_pred.extent
                test_pred.extend(torch.argmax(test_score.cpu().data, dim=1).numpy().tolist())

                pbar.update(1)

    result_output = pd.DataFrame(data={"id": test["id"], "sentiment": test_pred})
    result_output.to_csv("./result/gru.csv", index=False, quoting=3)
    logging.info('result saved!')

## imdb-roberta-trainer

In [14]:
pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (5.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.3.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.29.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (24.0.0)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.4.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.0 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6
Note: you may need to restart the kernel to use updated packages.

In [17]:
import os
import sys
import logging
import datasets
import evaluate

import pandas as pd
import numpy as np

from transformers import RobertaTokenizerFast, RobertaForSequenceClassification, DataCollatorWithPadding
from transformers import Trainer, TrainingArguments
from sklearn.model_selection import train_test_split

train = pd.read_csv("/kaggle/working/labeledTrainData.tsv", header=0, delimiter="\t", quoting=3)
test = pd.read_csv("/kaggle/working/testData.tsv", header=0, delimiter="\t", quoting=3)

if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)

    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info(r"running %s" % ''.join(sys.argv))

    train, val = train_test_split(train, test_size=.2)

    train_dict = {'label': train["sentiment"], 'text': train['review']}
    val_dict = {'label': val["sentiment"], 'text': val['review']}
    test_dict = {"text": test['review']}

    train_dataset = datasets.Dataset.from_dict(train_dict)
    val_dataset = datasets.Dataset.from_dict(val_dict)
    test_dataset = datasets.Dataset.from_dict(test_dict)

    tokenizer = RobertaTokenizerFast.from_pretrained('roberta-base')


    def preprocess_function(examples):
        return tokenizer(examples['text'], truncation=True)

    tokenized_train = train_dataset.map(preprocess_function, batched=True)
    tokenized_val = val_dataset.map(preprocess_function, batched=True)
    tokenized_test = test_dataset.map(preprocess_function, batched=True)

    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    model = RobertaForSequenceClassification.from_pretrained('roberta-base')

    metric = evaluate.load("accuracy")

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        predictions = logits.argmax(axis=-1)
        return metric.compute(predictions=predictions, references=labels)

    training_args = TrainingArguments(
        output_dir='./results',  # output directory
        num_train_epochs=3,  # total number of training epochs
        per_device_train_batch_size=4,  # batch size per device during training
        per_device_eval_batch_size=8,  # batch size for evaluation
        learning_rate=5e-6,
        warmup_steps=500,  # number of warmup steps for learning rate scheduler
        weight_decay=0.01,  # strength of weight decay
        logging_dir='./logs',  # directory for storing logs
        logging_steps=100,
        save_strategy="no",
        eval_strategy="epoch"
    )

    trainer = Trainer(
        model=model,  # the instantiated 🤗 Transformers model to be trained
        args=training_args,  # training arguments, defined above
        train_dataset=tokenized_train,  # training dataset
        eval_dataset=tokenized_val,  # evaluation dataset
        processing_class=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    trainer.train()

    prediction_outputs = trainer.predict(tokenized_test)
    test_pred = np.argmax(prediction_outputs[0], axis=-1).flatten()
    print(test_pred)

    result_output = pd.DataFrame(data={"id": test["id"], "sentiment": test_pred})
    result_output.to_csv("/kaggle/working/result/roberta_trainer.csv", index=False, quoting=3)
    logging.info('result saved!')

INFO:colab_kernel_launcher.py:running /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py-f/root/.local/share/jupyter/runtime/kernel-9d43de16-aa27-405b-8e98-a2b05b3731b3.json
INFO:httpx:HTTP Request: HEAD https://huggingface.co/roberta-base/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/roberta-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/FacebookAI/roberta-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/roberta-base/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/FacebookAI/roberta-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"

Map:   0%|          | 0/20000 [00:00<?, ? examples/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

INFO:httpx:HTTP Request: HEAD https://huggingface.co/roberta-base/resolve/main/config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/roberta-base/resolve/main/config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/roberta-base/resolve/main/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
classifier.dense.weight         | MISSING    |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

INFO:root:result saved!

[1 1 0 ... 0 1 1]

## imdb-transformer

In [5]:
import logging
import os
import sys
import time
import math
import re

import pandas as pd
import torch
from torch import nn
from torch import optim
from torch.nn import functional as F
from torch.autograd import Variable
from torch.nn.utils.rnn import pad_sequence, pack_padded_sequence
from tqdm import tqdm
from bs4 import BeautifulSoup
from collections import defaultdict, Counter
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


# test = pd.read_csv("/kaggle/working/testData.tsv", header=0, delimiter="\t", quoting=3)

num_epochs = 5
embed_size = 300
num_hiddens = 120
num_layers = 2
bidirectional = True
batch_size = 64
labels = 2
lr = 0.001
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
use_gpu = True


# Read data from files
train = pd.read_csv("/kaggle/working/labeledTrainData.tsv", header=0, delimiter="\t", quoting=3)
test = pd.read_csv("/kaggle/working/testData.tsv", header=0, delimiter="\t", quoting=3)


def review_to_wordlist(review, remove_stopwords=False):
    # Function to convert a document to a sequence of words,
    # optionally removing stop words.  Returns a list of words.
    #
    # 1. Remove HTML
    review_text = BeautifulSoup(review, "lxml").get_text()
    #
    # 2. Remove non-letters
    review_text = re.sub("[^a-zA-Z]", " ", review_text)
    #
    # 3. Convert words to lower case and split them
    words = review_text.lower().split()
    #
    # 4. Optionally remove stop words (false by default)
    # if remove_stopwords:
    #     stops = set(stopwords.words("english"))
    #     words = [w for w in words if not w in stops]
    #
    # 5. Return a list of words
    return ' '.join(words)


class Vocab:
    def __init__(self, tokens=None):
        self.idx_to_token = list()
        self.token_to_idx = dict()

        if tokens is not None:
            if "" not in tokens:
                tokens = tokens + [""]
            for token in tokens:
                self.idx_to_token.append(token)
                self.token_to_idx[token] = len(self.idx_to_token) - 1
            self.unk = self.token_to_idx['']

    @classmethod
    def build(cls, train, test, min_freq=1, reserved_tokens=None):
        token_freqs = defaultdict(int)
        for sentence in train:
            for token in sentence.split():
                token_freqs[token] += 1

        for sentence in test:
            for token in sentence.split():
                token_freqs[token] += 1

        uniq_tokens = [""] + (reserved_tokens if reserved_tokens else [])
        uniq_tokens += [token for token, freq in token_freqs.items() \
                        if freq >= min_freq and token != ""]
        return cls(uniq_tokens)

    def __len__(self):
        return len(self.idx_to_token)

    def __getitem__(self, token):
        return self.token_to_idx.get(token, self.unk)

    def convert_tokens_to_ids(self, tokens):
        return [self[token] for token in tokens]

    def convert_ids_to_tokens(self, indices):
        return [self.idx_to_token[index] for index in indices]


def length_to_mask(lengths):
    max_length = torch.max(lengths)
    # 动态获取 lengths 所在的设备 (CPU 或 CUDA)
    mask = torch.arange(max_length, device=lengths.device).expand(
        lengths.shape[0], max_length
    ) < lengths.unsqueeze(1)
    return mask


class PositionalEncoding(nn.Module):
    def __init__(self, d_model, dropout=0.1, max_len=10000):
        super(PositionalEncoding, self).__init__()

        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0).transpose(0, 1)
        self.register_buffer('pe', pe)

    def forward(self, x):
        x = x + self.pe[:x.size(0), :]
        return x


class Transformer(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, num_class,
                 dim_feedforward=512, num_head=2, num_layers=2, dropout=0.1, max_len=10000, activation: str = "relu"):
        super(Transformer, self).__init__()
        # 词嵌入层
        self.embedding_dim = embedding_dim
        self.embeddings = nn.Embedding(vocab_size, embedding_dim)
        # 线性投影层：将 embedding_dim (300) 投影到 hidden_dim (120)
        self.proj = nn.Linear(embedding_dim, hidden_dim)
        self.position_embedding = PositionalEncoding(hidden_dim, dropout, max_len)
        # 编码层：使用Transformer
        encoder_layer = nn.TransformerEncoderLayer(hidden_dim, num_head, dim_feedforward, dropout, activation)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers)
        # 输出层
        self.output = nn.Linear(hidden_dim, num_class)

    def forward(self, inputs, lengths):
        inputs = torch.transpose(inputs, 0, 1)
        hidden_states = self.embeddings(inputs)
        hidden_states = self.proj(hidden_states)
        hidden_states = self.position_embedding(hidden_states)
        attention_mask = length_to_mask(lengths) == False
        hidden_states = self.transformer(hidden_states, src_key_padding_mask=attention_mask)
        hidden_states = hidden_states[0, :, :]
        output = self.output(hidden_states)
        log_probs = F.log_softmax(output, dim=1)
        return log_probs


class TransformerDataset(torch.utils.data.Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, i):
        return self.data[i]


def collate_fn(examples):
    lengths = torch.tensor([len(ex[0]) for ex in examples])
    inputs = [torch.tensor(ex[0]) for ex in examples]
    targets = torch.tensor([ex[1] for ex in examples], dtype=torch.long)
    # 对batch内的样本进行padding，使其具有相同长度
    inputs = pad_sequence(inputs, batch_first=True)
    return inputs, lengths, targets


if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)

    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info(r"running %s" % ''.join(sys.argv))

    clean_train_reviews, train_labels = [], []
    for i, review in enumerate(train["review"]):
        clean_train_reviews.append(review_to_wordlist(review, remove_stopwords=False))
        train_labels.append(train["sentiment"][i])

    clean_test_reviews = []
    for review in test["review"]:
        clean_test_reviews.append(review_to_wordlist(review, remove_stopwords=False))

    vocab = Vocab.build(clean_train_reviews, clean_test_reviews)

    train_reviews = [(vocab.convert_tokens_to_ids(sentence.split()), train_labels[i])
                     for i, sentence in enumerate(clean_train_reviews)]
    # 给测试集构建二元组结构，便于复用 collate_fn
    test_reviews = [(vocab.convert_tokens_to_ids(sentence.split()), 0)
                    for sentence in clean_test_reviews]

    train_reviews, val_reviews = train_test_split(train_reviews, test_size=0.2, random_state=0)

    net = Transformer(vocab_size=len(vocab), embedding_dim=embed_size, hidden_dim=num_hiddens, num_class=labels)
    net.to(device)
    loss_function = nn.CrossEntropyLoss()
    optimizer = optim.Adam(net.parameters(), lr=lr)

    train_set = TransformerDataset(train_reviews)
    val_set = TransformerDataset(val_reviews)
    test_set = TransformerDataset(test_reviews)

    train_iter = torch.utils.data.DataLoader(train_set, collate_fn=collate_fn, batch_size=batch_size, shuffle=True)
    val_iter = torch.utils.data.DataLoader(val_set, collate_fn=collate_fn, batch_size=batch_size, shuffle=False)
    test_iter = torch.utils.data.DataLoader(test_set, collate_fn=collate_fn, batch_size=batch_size, shuffle=False)

    for epoch in range(num_epochs):
        start = time.time()
        train_loss, val_losses = 0, 0
        train_acc, val_acc = 0, 0
        n, m = 0, 0
        net.train()
        with tqdm(total=len(train_iter), desc='Epoch %d' % epoch) as pbar:
            for feature, lengths, label in train_iter:
                n += 1
                net.zero_grad()
                feature = feature.to(device)
                lengths = lengths.to(device)
                label = label.to(device)
                score = net(feature, lengths)
                loss = loss_function(score, label)
                loss.backward()
                optimizer.step()
                train_acc += accuracy_score(torch.argmax(score.cpu().data,
                                                         dim=1), label.cpu())
                train_loss += loss.item()

                pbar.set_postfix({'epoch': '%d' % (epoch),
                                  'train loss': '%.4f' % (train_loss / n),
                                  'train acc': '%.2f' % (train_acc / n)
                                  })
                pbar.update(1)

        net.eval()
        with torch.no_grad():
            for val_feature, val_length, val_label in val_iter:
                m += 1
                val_feature = val_feature.to(device)
                val_length = val_length.to(device)
                val_label = val_label.to(device)
                val_score = net(val_feature, val_length)
                val_loss = loss_function(val_score, val_label)
                val_acc += accuracy_score(torch.argmax(val_score.cpu().data, dim=1), val_label.cpu())
                val_losses += val_loss.item()
        end = time.time()
        runtime = end - start

        # tqdm.write('{epoch: %d, train loss: %.4f, train acc: %.2f, val loss: %.4f, val acc: %.2f, time: %.2f}' %
        #        (epoch, train_loss.data / n, train_acc / n, val_losses.data / m, val_acc / m, runtime))

    test_pred = []
    net.eval()
    os.makedirs("./result", exist_ok=True)
    with torch.no_grad():
        with tqdm(total=len(test_iter), desc='Prediction') as pbar:
            for test_feature, test_length, _ in test_iter:
                test_feature = test_feature.to(device)
                test_length = test_length.to(device)
                test_score = net(test_feature, test_length)
                # test_pred.extent
                test_pred.extend(torch.argmax(test_score.cpu().data, dim=1).numpy().tolist())

                pbar.update(1)

    result_output = pd.DataFrame(data={"id": test["id"], "sentiment": test_pred})
    result_output.to_csv("./result/transformer.csv", index=False, quoting=3)
    logging.info('result saved!')

2026-09-28 09:36:54,003: INFO: running /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py-f/root/.local/share/jupyter/runtime/kernel-e27e5644-e1ce-4f9e-89ca-7cc266484309.json
/tmp/ipykernel_58/3584162157.py:143: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  self.transformer = nn.TransformerEncoder(encoder_layer, num_layers)
Epoch 0: 100%|██████████| 313/313 [01:07<00:00,  4.65it/s, epoch=0, train loss=0.5780, train acc=0.67]
Epoch 1: 100%|██████████| 313/313 [01:06<00:00,  4.71it/s, epoch=1, train loss=0.2799, train acc=0.89]
Epoch 2: 100%|██████████| 313/313 [01:06<00:00,  4.70it/s, epoch=2, train loss=0.1796, train acc=0.93]
Epoch 3: 100%|██████████| 313/313 [01:06<00:00,  4.69it/s, epoch=3, train loss=0.1091, train acc=0.96]
Epoch 4: 100%|██████████| 313/313 [01:06<00:00,  4.68it/s, epoch=4, train loss=0.0694, train acc=0.98]
Prediction: 100%|██████████| 391/391 [00:18<00:00, 21.23it/s]
2026-09-28 09:43:24,880: INFO: result saved!

## imdb-bert-native

In [14]:
import os
import sys
import logging
import time

import pandas as pd
import torch
import torch.optim as optim
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score
from transformers import BertTokenizerFast, BertForSequenceClassification
from torch.optim import AdamW
from sklearn.model_selection import train_test_split
from tqdm import tqdm

train = pd.read_csv("/kaggle/working/labeledTrainData.tsv", header=0, delimiter="\t", quoting=3)
test = pd.read_csv("/kaggle/working/testData.tsv", header=0, delimiter="\t", quoting=3)


class TrainDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)


class TestDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, num_samples=0):
        self.encodings = encodings
        self.num_samples = num_samples

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        return item

    def __len__(self):
        return self.num_samples


if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)

    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info(r"running %s" % ''.join(sys.argv))

    train_texts, train_labels, test_texts = [], [], []
    for i, review in enumerate(train["review"]):
        train_texts.append(review)
        train_labels.append(train['sentiment'][i])

    for review in test['review']:
        test_texts.append(review)

    train_texts, val_texts, train_labels, val_labels = train_test_split(train_texts, train_labels, test_size=.2)

    tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')

    train_encodings = tokenizer(train_texts, truncation=True, padding=True)
    val_encodings = tokenizer(val_texts, truncation=True, padding=True)
    test_encodings = tokenizer(test_texts, truncation=True, padding=True)

    train_dataset = TrainDataset(train_encodings, train_labels)
    val_dataset = TrainDataset(val_encodings, val_labels)
    test_dataset = TestDataset(test_encodings, num_samples=len(test_texts))

    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

    model = BertForSequenceClassification.from_pretrained('bert-base-uncased')
    model.to(device)
    model.train()

    train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)

    optim = optim.AdamW(model.parameters(), lr=5e-5)

    for epoch in range(3):
        start = time.time()
        train_loss, val_losses = 0, 0
        train_acc, val_acc = 0, 0
        n, m = 0, 0

        with tqdm(total=len(train_loader), desc="Epoch %d" % epoch) as pbar:
            for batch in train_loader:
                n += 1
                optim.zero_grad()
                input_ids = batch['input_ids'].to(device)
                attention_mask = batch['attention_mask'].to(device)
                labels = batch['labels'].to(device)
                outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
                loss = outputs.loss
                loss.backward()
                optim.step()
                train_acc += accuracy_score(torch.argmax(outputs.logits.cpu().data, dim=1), labels.cpu())
                train_loss += loss.cpu()

                pbar.set_postfix({'epoch': '%d' % (epoch),
                                  'train loss': '%.4f' % (train_loss.data / n),
                                  'train acc': '%.2f' % (train_acc / n)
                                  })
                pbar.update(1)

            with torch.no_grad():
                for batch in val_loader:
                    m += 1
                    input_ids = batch['input_ids'].to(device)
                    attention_mask = batch['attention_mask'].to(device)
                    labels = batch['labels'].to(device)
                    outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
                    val_loss = outputs.loss
                    val_acc += accuracy_score(torch.argmax(outputs.logits.cpu().data, dim=1), labels.cpu())
                    val_losses += val_loss
            end = time.time()
            runtime = end - start
            pbar.set_postfix({'epoch': '%d' % (epoch),
                              'train loss': '%.4f' % (train_loss.data / n),
                              'train acc': '%.2f' % (train_acc / n),
                              'val loss': '%.4f' % (val_losses.data / m),
                              'val acc': '%.2f' % (val_acc / m),
                              'time': '%.2f' % (runtime)})

            # print('epoch: %d, train loss: %.4f, train acc: %.2f, val loss: %.4f, val acc: %.2f, time: %.2f' %
            #       (epoch, train_loss.data / n, train_acc / n, val_losses.data / m, val_acc / m, runtime))

    test_pred = []
    with torch.no_grad():
        with tqdm(total=len(test_loader), desc='Predction') as Pbar:
            for batch in test_loader:
                input_ids = batch['input_ids'].to(device)
                attention_mask = batch['attention_mask'].to(device)
                outputs = model(input_ids, attention_mask=attention_mask)
                # test_pred.extent
                test_pred.extend(torch.argmax(outputs.logits.cpu().data, dim=1).numpy().tolist())

                pbar.update(1)

    result_output = pd.DataFrame(data={"id": test["id"], "sentiment": test_pred})
    result_output.to_csv("./result/bert_native.csv", index=False, quoting=3)
    logging.info('result saved!')

INFO:colab_kernel_launcher.py:running /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py-f/root/.local/share/jupyter/runtime/kernel-f31ffe25-0c60-43f3-9afc-fd67af15430a.json
INFO:httpx:HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/bert-base-uncased/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/google-bert/bert-base-uncased/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/bert-base-uncased/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/google-bert/bert-base-uncased/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/vocab.txt "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://huggingface.co/bert-base-uncased/resolve/main/vocab.txt "HTTP/1.1 200 OK"

vocab.txt: 0.00B [00:00, ?B/s]

INFO:httpx:HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://huggingface.co/bert-base-uncased/resolve/main/tokenizer.json "HTTP/1.1 200 OK"

tokenizer.json: 0.00B [00:00, ?B/s]

INFO:httpx:HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/special_tokens_map.json "HTTP/1.1 404 Not Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://huggingface.co/bert-base-uncased/resolve/main/config.json "HTTP/1.1 200 OK"

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

INFO:httpx:HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/config.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/model.safetensors "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/google-bert/bert-base-uncased/xet-read-token/86b5e0934494bd15c9632b12f734a8a67f723594 "HTTP/1.1 200 OK"

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Epoch 0: 100%|██████████| 2500/2500 [39:36<00:00,  1.05it/s, epoch=0, train loss=0.2930, train acc=0.88, val loss=0.2548, val acc=0.89, time=2376.19]
Epoch 1: 100%|██████████| 2500/2500 [39:31<00:00,  1.05it/s, epoch=1, train loss=0.1618, train acc=0.94, val loss=0.2155, val acc=0.92, time=2371.79]
Epoch 2: 100%|██████████| 2500/2500 [39:32<00:00,  1.05it/s, epoch=2, train loss=0.1056, train acc=0.96, val loss=0.2418, val acc=0.92, time=2373.01]
Predction:   0%|          | 0/1563 [15:50<?, ?it/s]
INFO:root:result saved!

## imdb-bert-scratch

In [2]:
pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (5.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.3.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.29.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (24.0.0)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.4.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.2 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6
Note: you may need to restart the kernel to use updated packages.

In [3]:
import os
import sys
import logging
import datasets

import torch.nn as nn

import pandas as pd
import numpy as np
import evaluate

from transformers import BertTokenizerFast, DataCollatorWithPadding
from transformers import Trainer, TrainingArguments
from transformers import BertPreTrainedModel, BertModel
from transformers.modeling_outputs import SequenceClassifierOutput

from sklearn.model_selection import train_test_split

train = pd.read_csv("/kaggle/working/labeledTrainData.tsv", header=0, delimiter="\t", quoting=3)
test = pd.read_csv("/kaggle/working/testData.tsv", header=0, delimiter="\t", quoting=3)


class BertScratch(BertPreTrainedModel):

    @classmethod
    def _can_set_experts_implementation(cls):
        return False
    
    def __init__(self, config):
        super().__init__(config)
        self.num_labels = config.num_labels
        self.config = config

        self.bert = BertModel(config)
        classifier_dropout = (
            config.classifier_dropout if config.classifier_dropout is not None else config.hidden_dropout_prob
        )
        self.dropout = nn.Dropout(classifier_dropout)
        self.classifier = nn.Linear(config.hidden_size, config.num_labels)

        self.post_init()

    def forward(self, input_ids=None, attention_mask=None, token_type_ids=None, labels=None):
        outputs = self.bert(input_ids, attention_mask, token_type_ids)

        pooled_output = outputs[1]

        pooled_output = self.dropout(pooled_output)
        logits = self.classifier(pooled_output)

        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()
            loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))
        
        return SequenceClassifierOutput(
            loss=loss,
            logits=logits,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions
        )


if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)

    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info(r"running %s" % ''.join(sys.argv))

    train, val = train_test_split(train, test_size=.2)

    train_dict = {'label': train["sentiment"], 'text': train['review']}
    val_dict = {'label': val["sentiment"], 'text': val['review']}
    test_dict = {"text": test['review']}

    train_dataset = datasets.Dataset.from_dict(train_dict)
    val_dataset = datasets.Dataset.from_dict(val_dict)
    test_dataset = datasets.Dataset.from_dict(test_dict)

    tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')


    def preprocess_function(examples):
        return tokenizer(examples['text'], truncation=True)


    tokenized_train = train_dataset.map(preprocess_function, batched=True)
    tokenized_val = val_dataset.map(preprocess_function, batched=True)
    tokenized_test = test_dataset.map(preprocess_function, batched=True)

    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    model = BertScratch.from_pretrained('bert-base-uncased')

    metric = evaluate.load("accuracy")


    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        predictions = np.argmax(logits, axis=-1)
        return metric.compute(predictions=predictions, references=labels)


    training_args = TrainingArguments(
        output_dir='./checkpoint',  # output directory
        num_train_epochs=3,  # total number of training epochs
        per_device_train_batch_size=6,  # batch size per device during training
        per_device_eval_batch_size=12,  # batch size for evaluation
        warmup_steps=500,  # number of warmup steps for learning rate scheduler
        weight_decay=0.01,  # strength of weight decay
        logging_dir='./logs',  # directory for storing logs
        logging_steps=100,
        save_strategy="no",
        eval_strategy="epoch"
    )

    trainer = Trainer(
        model=model,  # the instantiated 🤗 Transformers model to be trained
        args=training_args,  # training arguments, defined above
        train_dataset=tokenized_train,  # training dataset
        eval_dataset=tokenized_val,  # evaluation dataset
        processing_class=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    trainer.train()

    prediction_outputs = trainer.predict(tokenized_test)
    test_pred = np.argmax(prediction_outputs[0], axis=-1).flatten()
    print(test_pred)

    result_output = pd.DataFrame(data={"id": test["id"], "sentiment": test_pred})
    result_output.to_csv("./result/bert_scratch.csv", index=False, quoting=3)
    logging.info('result saved!')

2026-09-29 12:49:09,932: INFO: running /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py-f/root/.local/share/jupyter/runtime/kernel-646c3094-15d0-4ddf-9506-fa8c8f0edda6.json
2026-09-29 12:49:10,646: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
2026-09-29 12:49:10,709: INFO: HTTP Request: GET https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-09-29 12:49:10,710: WARNING: Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

2026-09-29 12:49:10,767: INFO: HTTP Request: GET https://huggingface.co/api/models/bert-base-uncased/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-09-29 12:49:10,804: INFO: HTTP Request: GET https://huggingface.co/api/models/google-bert/bert-base-uncased/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-09-29 12:49:10,842: INFO: HTTP Request: GET https://huggingface.co/api/models/bert-base-uncased/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-09-29 12:49:10,884: INFO: HTTP Request: GET https://huggingface.co/api/models/google-bert/bert-base-uncased/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-09-29 12:49:10,925: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/vocab.txt "HTTP/1.1 200 OK"
2026-09-29 12:49:10,968: INFO: HTTP Request: GET https://huggingface.co/bert-base-uncased/resolve/main/vocab.txt "HTTP/1.1 200 OK"

vocab.txt: 0.00B [00:00, ?B/s]

2026-09-29 12:49:11,051: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer.json "HTTP/1.1 200 OK"
2026-09-29 12:49:11,097: INFO: HTTP Request: GET https://huggingface.co/bert-base-uncased/resolve/main/tokenizer.json "HTTP/1.1 200 OK"

tokenizer.json: 0.00B [00:00, ?B/s]

2026-09-29 12:49:11,164: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
2026-09-29 12:49:11,205: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/special_tokens_map.json "HTTP/1.1 404 Not Found"
2026-09-29 12:49:11,246: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"

Map:   0%|          | 0/20000 [00:00<?, ? examples/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

2026-09-29 12:49:37,770: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/config.json "HTTP/1.1 200 OK"
2026-09-29 12:49:37,816: INFO: HTTP Request: GET https://huggingface.co/bert-base-uncased/resolve/main/config.json "HTTP/1.1 200 OK"

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

2026-09-29 12:49:37,872: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-09-29 12:49:37,913: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/config.json "HTTP/1.1 200 OK"
2026-09-29 12:49:37,956: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/model.safetensors "HTTP/1.1 302 Found"
2026-09-29 12:49:38,052: INFO: HTTP Request: GET https://huggingface.co/api/models/google-bert/bert-base-uncased/xet-read-token/86b5e0934494bd15c9632b12f734a8a67f723594 "HTTP/1.1 200 OK"

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertScratch LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Downloading builder script: 0.00B [00:00, ?B/s]

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

2026-09-29 14:01:10,355: INFO: result saved!

[1 0 0 ... 0 1 1]

## imdb-bert-trainer

In [6]:
import os
import sys
import logging
import datasets

import pandas as pd
import numpy as np
import evaluate

from transformers import BertTokenizerFast, BertForSequenceClassification, DataCollatorWithPadding
from transformers import Trainer, TrainingArguments
from sklearn.model_selection import train_test_split

train = pd.read_csv("/kaggle/working/labeledTrainData.tsv", header=0, delimiter="\t", quoting=3)
test = pd.read_csv("/kaggle/working/testData.tsv", header=0, delimiter="\t", quoting=3)

if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)

    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info(r"running %s" % ''.join(sys.argv))

    train, val = train_test_split(train, test_size=.2)

    train_dict = {'label': train["sentiment"], 'text': train['review']}
    val_dict = {'label': val["sentiment"], 'text': val['review']}
    test_dict = {"text": test['review']}

    train_dataset = datasets.Dataset.from_dict(train_dict)
    val_dataset = datasets.Dataset.from_dict(val_dict)
    test_dataset = datasets.Dataset.from_dict(test_dict)

    tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')


    def preprocess_function(examples):
        return tokenizer(examples['text'], truncation=True)

    tokenized_train = train_dataset.map(preprocess_function, batched=True)
    tokenized_val = val_dataset.map(preprocess_function, batched=True)
    tokenized_test = test_dataset.map(preprocess_function, batched=True)

    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    model = BertForSequenceClassification.from_pretrained('bert-base-uncased')

    metric = evaluate.load("accuracy")


    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        predictions = np.argmax(logits, axis=-1)
        return metric.compute(predictions=predictions, references=labels)


    training_args = TrainingArguments(
        output_dir='./checkpoint',  # output directory
        num_train_epochs=3,  # total number of training epochs
        per_device_train_batch_size=16,  # batch size per device during training
        per_device_eval_batch_size=32,  # batch size for evaluation
        warmup_steps=500,  # number of warmup steps for learning rate scheduler
        weight_decay=0.01,  # strength of weight decay
        logging_dir='./logs',  # directory for storing logs
        logging_steps=100,
        save_strategy="no",
        eval_strategy="epoch"
    )

    trainer = Trainer(
        model=model,  # the instantiated 🤗 Transformers model to be trained
        args=training_args,  # training arguments, defined above
        train_dataset=tokenized_train,  # training dataset
        eval_dataset=tokenized_val,  # evaluation dataset
        processing_class=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    trainer.train()

    prediction_outputs = trainer.predict(tokenized_test)
    test_pred = np.argmax(prediction_outputs[0], axis=-1).flatten()
    print(test_pred)

    result_output = pd.DataFrame(data={"id": test["id"], "sentiment": test_pred})
    result_output.to_csv("./result/bert_trainer.csv", index=False, quoting=3)
    logging.info('result saved!')

2026-09-29 14:42:10,418: INFO: running /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py-f/root/.local/share/jupyter/runtime/kernel-646c3094-15d0-4ddf-9506-fa8c8f0edda6.json
2026-09-29 14:42:11,032: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
2026-09-29 14:42:11,076: INFO: HTTP Request: GET https://huggingface.co/api/models/bert-base-uncased/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-09-29 14:42:11,120: INFO: HTTP Request: GET https://huggingface.co/api/models/google-bert/bert-base-uncased/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-09-29 14:42:11,160: INFO: HTTP Request: GET https://huggingface.co/api/models/bert-base-uncased/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-09-29 14:42:11,203: INFO: HTTP Request: GET https://huggingface.co/api/models/google-bert/bert-base-uncased/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"

Map:   0%|          | 0/20000 [00:00<?, ? examples/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

2026-09-29 14:42:37,502: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/config.json "HTTP/1.1 200 OK"
2026-09-29 14:42:37,543: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/config.json "HTTP/1.1 200 OK"
2026-09-29 14:42:37,588: INFO: HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

2026-09-29 15:47:09,204: INFO: result saved!

[1 0 0 ... 0 1 1]

## imdb-distilbert-native

In [2]:
import os
import sys
import logging
import time

import pandas as pd
import torch.optim as optim

import torch
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification
from sklearn.model_selection import train_test_split
from tqdm import tqdm

train = pd.read_csv("/kaggle/working/labeledTrainData.tsv", header=0,
                    delimiter="\t", quoting=3)
test = pd.read_csv("/kaggle/working/testData.tsv", header=0,
                    delimiter="\t", quoting=3)


class TrainDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        if labels:
            self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        if self.labels:
            item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)


class TestDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, num_samples=0):
        self.encodings = encodings
        self.num_samples = num_samples

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        return item

    def __len__(self):
        return self.num_samples


if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)

    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info(r"running %s" % ''.join(sys.argv))

    train_texts, train_labels, test_texts = [], [], []
    for i, review in enumerate(train["review"]):
        train_texts.append(review)
        train_labels.append(train['sentiment'][i])

    for review in test['review']:
        test_texts.append(review)

    train_texts, val_texts, train_labels, val_labels = train_test_split(train_texts, train_labels, test_size=.2)

    tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

    train_encodings = tokenizer(train_texts, truncation=True, padding=True)
    val_encodings = tokenizer(val_texts, truncation=True, padding=True)
    test_encodings = tokenizer(test_texts, truncation=True, padding=True)

    train_dataset = TrainDataset(train_encodings, train_labels)
    val_dataset = TrainDataset(val_encodings, val_labels)
    test_dataset = TestDataset(test_encodings, num_samples=len(test_texts))

    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

    model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
    model.to(device)
    model.train()

    train_loader = DataLoader(train_dataset, batch_size=12, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=24, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=24, shuffle=False)

    optim = optim.AdamW(model.parameters(), lr=5e-5)

    for epoch in range(3):
        start = time.time()
        train_loss, val_losses = 0, 0
        train_acc, val_acc = 0, 0
        n, m = 0, 0

        with tqdm(total=len(train_loader), desc="Epoch %d" % epoch) as pbar:
            for batch in train_loader:
                n += 1
                optim.zero_grad()
                input_ids = batch['input_ids'].to(device)
                attention_mask = batch['attention_mask'].to(device)
                labels = batch['labels'].to(device)
                outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
                loss = outputs.loss
                loss.backward()
                optim.step()
                train_acc += accuracy_score(torch.argmax(outputs.logits.cpu().data, dim=1), labels.cpu())
                train_loss += loss.cpu()

                pbar.set_postfix({'epoch': '%d' % (epoch),
                                  'train loss': '%.4f' % (train_loss.data / n),
                                  'train acc': '%.2f' % (train_acc / n)
                                  })
                pbar.update(1)

            with torch.no_grad():
                for batch in val_loader:
                    m += 1
                    input_ids = batch['input_ids'].to(device)
                    attention_mask = batch['attention_mask'].to(device)
                    labels = batch['labels'].to(device)
                    outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
                    val_loss = outputs.loss
                    val_acc += accuracy_score(torch.argmax(outputs.logits.cpu().data, dim=1), labels.cpu())
                    val_losses += val_loss
            end = time.time()
            runtime = end - start
            pbar.set_postfix({'epoch': '%d' % (epoch),
                              'train loss': '%.4f' % (train_loss.data / n),
                              'train acc': '%.2f' % (train_acc / n),
                              'val loss': '%.4f' % (val_losses.data / m),
                              'val acc': '%.2f' % (val_acc / m),
                              'time': '%.2f' % (runtime)})

            # print('epoch: %d, train loss: %.4f, train acc: %.2f, val loss: %.4f, val acc: %.2f, time: %.2f' %
            #       (epoch, train_loss.data / n, train_acc / n, val_losses.data / m, val_acc / m, runtime))

    test_pred = []
    with torch.no_grad():
        with tqdm(total=len(test_loader), desc='Predction') as pbar:
            for batch in test_loader:
                input_ids = batch['input_ids'].to(device)
                attention_mask = batch['attention_mask'].to(device)
                outputs = model(input_ids, attention_mask=attention_mask)
                # test_pred.extent
                test_pred.extend(torch.argmax(outputs.logits.cpu().data, dim=1).numpy().tolist())

                pbar.update(1)

    result_output = pd.DataFrame(data={"id": test["id"], "sentiment": test_pred})
    result_output.to_csv("./result/distilbert_native.csv", index=False, quoting=3)
    logging.info('result saved!')

2026-09-30 08:47:49,112: INFO: running /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py-f/root/.local/share/jupyter/runtime/kernel-3b5ea41c-a272-4bec-965d-1325136fcf2f.json
2026-09-30 08:47:49,310: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-09-30 08:47:49,311: WARNING: Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-09-30 08:47:49,332: INFO: HTTP Request: GET https://huggingface.co/distilbert-base-uncased/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

2026-09-30 08:47:49,361: INFO: HTTP Request: GET https://huggingface.co/api/models/distilbert-base-uncased/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-09-30 08:47:49,379: INFO: HTTP Request: GET https://huggingface.co/api/models/distilbert/distilbert-base-uncased/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-09-30 08:47:49,396: INFO: HTTP Request: GET https://huggingface.co/api/models/distilbert-base-uncased/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-09-30 08:47:49,413: INFO: HTTP Request: GET https://huggingface.co/api/models/distilbert/distilbert-base-uncased/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-09-30 08:47:49,431: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/vocab.txt "HTTP/1.1 200 OK"
2026-09-30 08:47:49,450: INFO: HTTP Request: GET https://huggingface.co/distilbert-base-uncased/resolve/main/vocab.txt "HTTP/1.1 200 OK"

vocab.txt: 0.00B [00:00, ?B/s]

2026-09-30 08:47:49,489: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/tokenizer.json "HTTP/1.1 200 OK"
2026-09-30 08:47:49,510: INFO: HTTP Request: GET https://huggingface.co/distilbert-base-uncased/resolve/main/tokenizer.json "HTTP/1.1 200 OK"

tokenizer.json: 0.00B [00:00, ?B/s]

2026-09-30 08:47:49,546: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
2026-09-30 08:47:49,568: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/special_tokens_map.json "HTTP/1.1 404 Not Found"
2026-09-30 08:47:49,585: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
2026-09-30 08:48:10,445: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/config.json "HTTP/1.1 200 OK"
2026-09-30 08:48:10,470: INFO: HTTP Request: GET https://huggingface.co/distilbert-base-uncased/resolve/main/config.json "HTTP/1.1 200 OK"

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

2026-09-30 08:48:10,499: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-09-30 08:48:10,533: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/config.json "HTTP/1.1 200 OK"
2026-09-30 08:48:10,566: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/model.safetensors "HTTP/1.1 302 Found"
2026-09-30 08:48:10,630: INFO: HTTP Request: GET https://huggingface.co/api/models/distilbert/distilbert-base-uncased/xet-read-token/12040accade4e8a0f71eabdb258fecc2e7e948be "HTTP/1.1 200 OK"

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Epoch 0: 100%|██████████| 1667/1667 [19:03<00:00,  1.46it/s, epoch=0, train loss=0.2807, train acc=0.88, val loss=0.2113, val acc=0.92, time=1143.85]
Epoch 1: 100%|██████████| 1667/1667 [19:11<00:00,  1.45it/s, epoch=1, train loss=0.1459, train acc=0.95, val loss=0.2213, val acc=0.91, time=1151.86]
Epoch 2: 100%|██████████| 1667/1667 [19:11<00:00,  1.45it/s, epoch=2, train loss=0.0769, train acc=0.97, val loss=0.2983, val acc=0.91, time=1152.19]
Predction: 100%|██████████| 1042/1042 [07:03<00:00,  2.46it/s]
2026-09-30 09:52:45,279: INFO: result saved!

## imdb-distilbert-trainer

In [1]:
!pip install -q evaluate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.1 MB/s eta 0:00:00a 0:00:01

In [6]:
import os
import sys
import logging
import datasets

import pandas as pd
import numpy as np
import evaluate

from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification, DataCollatorWithPadding
from transformers import Trainer, TrainingArguments
from sklearn.model_selection import train_test_split

train = pd.read_csv("/kaggle/working/labeledTrainData.tsv", header=0, delimiter="\t", quoting=3)
test = pd.read_csv("/kaggle/working/testData.tsv", header=0, delimiter="\t", quoting=3)

if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)

    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info(r"running %s" % ''.join(sys.argv))

    train, val = train_test_split(train, test_size=.2)

    train_dict = {'label': train["sentiment"], 'text': train['review']}
    val_dict = {'label': val["sentiment"], 'text': val['review']}
    test_dict = {"text": test['review']}

    train_dataset = datasets.Dataset.from_dict(train_dict)
    val_dataset = datasets.Dataset.from_dict(val_dict)
    test_dataset = datasets.Dataset.from_dict(test_dict)

    tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')


    def preprocess_function(examples):
        return tokenizer(examples['text'], truncation=True)

    tokenized_train = train_dataset.map(preprocess_function, batched=True)
    tokenized_val = val_dataset.map(preprocess_function, batched=True)
    tokenized_test = test_dataset.map(preprocess_function, batched=True)

    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')

    metric = evaluate.load("accuracy")

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        predictions = np.argmax(logits, axis=-1)
        return metric.compute(predictions=predictions, references=labels)


    training_args = TrainingArguments(
        output_dir='./results',  # output directory
        num_train_epochs=3,  # total number of training epochs
        per_device_train_batch_size=12,  # batch size per device during training
        per_device_eval_batch_size=24,  # batch size for evaluation
        warmup_steps=500,  # number of warmup steps for learning rate scheduler
        weight_decay=0.01,  # strength of weight decay
        logging_dir='./logs',  # directory for storing logs
        logging_steps=100,
        save_strategy="no",
        eval_strategy="epoch"
    )

    trainer = Trainer(
        model=model,  # the instantiated 🤗 Transformers model to be trained
        args=training_args,  # training arguments, defined above
        train_dataset=tokenized_train,  # training dataset
        eval_dataset=tokenized_val,  # evaluation dataset
        processing_class=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    trainer.train()

    prediction_outputs = trainer.predict(tokenized_test)
    test_pred = np.argmax(prediction_outputs[0], axis=-1).flatten()
    print(test_pred)

    result_output = pd.DataFrame(data={"id": test["id"], "sentiment": test_pred})
    result_output.to_csv("./result/distilbert_trainer.csv", index=False, quoting=3)
    logging.info('result saved!')

2026-09-30 14:21:23,912: INFO: running /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py-f/root/.local/share/jupyter/runtime/kernel-e626f1eb-9bc6-4e3a-9167-8788755fb979.json
2026-09-30 14:21:24,481: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
2026-09-30 14:21:24,522: INFO: HTTP Request: GET https://huggingface.co/api/models/distilbert-base-uncased/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-09-30 14:21:24,561: INFO: HTTP Request: GET https://huggingface.co/api/models/distilbert/distilbert-base-uncased/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-09-30 14:21:24,601: INFO: HTTP Request: GET https://huggingface.co/api/models/distilbert-base-uncased/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-09-30 14:21:24,642: INFO: HTTP Request: GET https://huggingface.co/api/models/distilbert/distilbert-base-uncased/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"

Map:   0%|          | 0/20000 [00:00<?, ? examples/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

2026-09-30 14:21:49,383: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/config.json "HTTP/1.1 200 OK"
2026-09-30 14:21:49,424: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/config.json "HTTP/1.1 200 OK"
2026-09-30 14:21:49,469: INFO: HTTP Request: HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

2026-09-30 14:55:31,914: INFO: result saved!

[1 0 0 ... 0 1 1]